
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class test
	{
		public virtual void Build ()
		{
			// Action group xPLduinoManager.test
		}
	}
}
