
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class ChangePreferences
	{
		private global::Gtk.Notebook MainNoteBook;
		private global::Gtk.Notebook GeneralNoteBook;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label StartLabel;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label7;
		private global::Gtk.CheckButton DisplayWelcomeTab;
		private global::Gtk.Label EndLabel;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label8;
		private global::Gtk.CheckButton ConfirmClose;
		private global::Gtk.Label StartTab;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label VariousLabel;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label label9;
		private global::Gtk.CheckButton BeepOnDelete;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label label10;
		private global::Gtk.CheckButton BeepOnError;
		private global::Gtk.Label VariousTab;
		private global::Gtk.Label GeneralLabelTab;
		private global::Gtk.Notebook GeneralNoteBook1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label LangageLabel;
		private global::Gtk.HBox hbox7;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Label label11;
		private global::Gtk.RadioButton FrenchRadioButton;
		private global::Gtk.RadioButton EnglishRadioButton;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Label InterfaceTab;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label VariousLabel1;
		private global::Gtk.HBox hbox10;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Label OngletTab;
		private global::Gtk.Label InterfaceLabelTab;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label LIGDefaultValueLabel;
		private global::Gtk.HBox hbox12;
		private global::Gtk.HBox hbox13;
		private global::Gtk.Label label12;
		private global::Gtk.Label DefaultValueLabel;
		private global::Gtk.SpinButton SpinButtonDefaultValue;
		private global::Gtk.HBox hbox14;
		private global::Gtk.Label label13;
		private global::Gtk.Label FadeLabel;
		private global::Gtk.SpinButton SpinButtonFade;
		private global::Gtk.Label LIGActionLabel;
		private global::Gtk.HBox hbox21;
		private global::Gtk.HBox hbox22;
		private global::Gtk.Label label18;
		private global::Gtk.Label LIGToogleLabel;
		private global::Gtk.Entry LIGEntryToggle;
		private global::Gtk.HBox hbox23;
		private global::Gtk.HBox hbox24;
		private global::Gtk.Label label19;
		private global::Gtk.Label LIGTuneLabel;
		private global::Gtk.Entry LIGEntryTune;
		private global::Gtk.HBox hbox25;
		private global::Gtk.HBox hbox26;
		private global::Gtk.Label label20;
		private global::Gtk.Label LIGStopTuneLabel;
		private global::Gtk.Entry LIGEntryStop;
		private global::Gtk.HBox hbox39;
		private global::Gtk.Label label33;
		private global::Gtk.Label LIGSetValueLabel;
		private global::Gtk.Entry LIGEntrySetValue;
		private global::Gtk.Label LightingLabelTab;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label SWIDefaultValueLabel;
		private global::Gtk.HBox hbox15;
		private global::Gtk.HBox hbox16;
		private global::Gtk.Label label14;
		private global::Gtk.Label InverseLabel;
		private global::Gtk.CheckButton CheckButtonInverse;
		private global::Gtk.HBox hbox17;
		private global::Gtk.Label label15;
		private global::Gtk.Label ImpulstionTimeLabel;
		private global::Gtk.SpinButton SpinButtonImpulsionTime;
		private global::Gtk.Label SWIActionLabel;
		private global::Gtk.HBox hbox27;
		private global::Gtk.Label label21;
		private global::Gtk.Label SWIClicLabel;
		private global::Gtk.Entry SWIEntryClic;
		private global::Gtk.HBox hbox28;
		private global::Gtk.Label label22;
		private global::Gtk.Label SWIDoubleClicLabel;
		private global::Gtk.Entry SWIEntryDoubleClic;
		private global::Gtk.HBox hbox29;
		private global::Gtk.Label label23;
		private global::Gtk.Label SWIOnLabel;
		private global::Gtk.Entry SWIEntryOn;
		private global::Gtk.HBox hbox30;
		private global::Gtk.Label label24;
		private global::Gtk.Label SWIOnFmLabel;
		private global::Gtk.Entry SWIEntryOnFm;
		private global::Gtk.HBox hbox31;
		private global::Gtk.Label label25;
		private global::Gtk.Label SWIOffLabel;
		private global::Gtk.Entry SWIEntryOff;
		private global::Gtk.HBox hbox32;
		private global::Gtk.Label label26;
		private global::Gtk.Label SWIOffFmLabel;
		private global::Gtk.Entry SWIEntryOffFm;
		private global::Gtk.Label SwitchLabelTab;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label SHUDefaultValueLabel;
		private global::Gtk.HBox hbox18;
		private global::Gtk.HBox hbox19;
		private global::Gtk.Label label16;
		private global::Gtk.Label ShutterTypeLabel;
		private global::Gtk.ComboBox ComboboxShutterType;
		private global::Gtk.HBox hbox20;
		private global::Gtk.Label label17;
		private global::Gtk.Label TravelTimeLabel;
		private global::Gtk.SpinButton SpinButtonTravelTime;
		private global::Gtk.HBox hbox36;
		private global::Gtk.Label label30;
		private global::Gtk.Label InitTimeLabel;
		private global::Gtk.SpinButton SpinButtonInitTime;
		private global::Gtk.Label SHUActionLabel;
		private global::Gtk.HBox hbox33;
		private global::Gtk.Label label27;
		private global::Gtk.Label SHUOpenLabel;
		private global::Gtk.Entry SHUEntryOpen;
		private global::Gtk.HBox hbox34;
		private global::Gtk.Label label28;
		private global::Gtk.Label SHUCloseLabel;
		private global::Gtk.Entry SHUEntryClose;
		private global::Gtk.HBox hbox35;
		private global::Gtk.Label label29;
		private global::Gtk.Label SHUStopLabel;
		private global::Gtk.Entry SHUEntryStop;
		private global::Gtk.HBox hbox37;
		private global::Gtk.Label label31;
		private global::Gtk.Label SHUToggleLabel;
		private global::Gtk.Entry SHUEntryToggle;
		private global::Gtk.Label ShutterLabelTab;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Label TEMPActionLabel;
		private global::Gtk.HBox hbox38;
		private global::Gtk.Label label32;
		private global::Gtk.Label TEMPGetLabel;
		private global::Gtk.Entry TEMPEntryGet;
		private global::Gtk.Label TemperatureLabelTab;
		private global::Gtk.Label ErrorLabel;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.ChangePreferences
			this.Name = "xPLduinoManager.ChangePreferences";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child xPLduinoManager.ChangePreferences.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.MainNoteBook = new global::Gtk.Notebook ();
			this.MainNoteBook.CanFocus = true;
			this.MainNoteBook.Name = "MainNoteBook";
			this.MainNoteBook.CurrentPage = 2;
			this.MainNoteBook.TabPos = ((global::Gtk.PositionType)(0));
			this.MainNoteBook.ShowBorder = false;
			// Container child MainNoteBook.Gtk.Notebook+NotebookChild
			this.GeneralNoteBook = new global::Gtk.Notebook ();
			this.GeneralNoteBook.CanFocus = true;
			this.GeneralNoteBook.Name = "GeneralNoteBook";
			this.GeneralNoteBook.CurrentPage = 0;
			// Container child GeneralNoteBook.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.StartLabel = new global::Gtk.Label ();
			this.StartLabel.Name = "StartLabel";
			this.StartLabel.Xpad = 10;
			this.StartLabel.Xalign = 0F;
			this.StartLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
			this.vbox3.Add (this.StartLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.StartLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xpad = 10;
			this.hbox3.Add (this.label7);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label7]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.DisplayWelcomeTab = new global::Gtk.CheckButton ();
			this.DisplayWelcomeTab.CanFocus = true;
			this.DisplayWelcomeTab.Name = "DisplayWelcomeTab";
			this.DisplayWelcomeTab.Label = global::Mono.Unix.Catalog.GetString ("Welcome tab in start");
			this.DisplayWelcomeTab.DrawIndicator = true;
			this.DisplayWelcomeTab.UseUnderline = true;
			this.hbox3.Add (this.DisplayWelcomeTab);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.DisplayWelcomeTab]));
			w4.Position = 1;
			this.hbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
			w5.Position = 0;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.EndLabel = new global::Gtk.Label ();
			this.EndLabel.Name = "EndLabel";
			this.EndLabel.Xpad = 10;
			this.EndLabel.Xalign = 0F;
			this.EndLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Stop");
			this.vbox3.Add (this.EndLabel);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.EndLabel]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xpad = 10;
			this.hbox4.Add (this.label8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label8]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ConfirmClose = new global::Gtk.CheckButton ();
			this.ConfirmClose.CanFocus = true;
			this.ConfirmClose.Name = "ConfirmClose";
			this.ConfirmClose.Label = global::Mono.Unix.Catalog.GetString ("Ask before to close");
			this.ConfirmClose.Active = true;
			this.ConfirmClose.DrawIndicator = true;
			this.ConfirmClose.UseUnderline = true;
			this.hbox4.Add (this.ConfirmClose);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ConfirmClose]));
			w9.Position = 1;
			this.vbox3.Add (this.hbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox4]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			this.GeneralNoteBook.Add (this.vbox3);
			// Notebook tab
			this.StartTab = new global::Gtk.Label ();
			this.StartTab.Name = "StartTab";
			this.StartTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Start");
			this.GeneralNoteBook.SetTabLabel (this.vbox3, this.StartTab);
			this.StartTab.ShowAll ();
			// Container child GeneralNoteBook.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.VariousLabel = new global::Gtk.Label ();
			this.VariousLabel.Name = "VariousLabel";
			this.VariousLabel.Xpad = 10;
			this.VariousLabel.Xalign = 0F;
			this.VariousLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Various");
			this.vbox2.Add (this.VariousLabel);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.VariousLabel]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xpad = 10;
			this.hbox5.Add (this.label9);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label9]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.BeepOnDelete = new global::Gtk.CheckButton ();
			this.BeepOnDelete.CanFocus = true;
			this.BeepOnDelete.Name = "BeepOnDelete";
			this.BeepOnDelete.Label = global::Mono.Unix.Catalog.GetString ("Beep on delete");
			this.BeepOnDelete.DrawIndicator = true;
			this.BeepOnDelete.UseUnderline = true;
			this.hbox5.Add (this.BeepOnDelete);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.BeepOnDelete]));
			w14.Position = 1;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xpad = 10;
			this.hbox6.Add (this.label10);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label10]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.BeepOnError = new global::Gtk.CheckButton ();
			this.BeepOnError.CanFocus = true;
			this.BeepOnError.Name = "BeepOnError";
			this.BeepOnError.Label = global::Mono.Unix.Catalog.GetString ("Beep on error");
			this.BeepOnError.DrawIndicator = true;
			this.BeepOnError.UseUnderline = true;
			this.hbox6.Add (this.BeepOnError);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.BeepOnError]));
			w17.Position = 1;
			this.vbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox6]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.GeneralNoteBook.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w19 = ((global::Gtk.Notebook.NotebookChild)(this.GeneralNoteBook [this.vbox2]));
			w19.Position = 1;
			// Notebook tab
			this.VariousTab = new global::Gtk.Label ();
			this.VariousTab.Name = "VariousTab";
			this.VariousTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Various");
			this.GeneralNoteBook.SetTabLabel (this.vbox2, this.VariousTab);
			this.VariousTab.ShowAll ();
			this.MainNoteBook.Add (this.GeneralNoteBook);
			// Notebook tab
			this.GeneralLabelTab = new global::Gtk.Label ();
			this.GeneralLabelTab.Name = "GeneralLabelTab";
			this.GeneralLabelTab.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.MainNoteBook.SetTabLabel (this.GeneralNoteBook, this.GeneralLabelTab);
			this.GeneralLabelTab.ShowAll ();
			// Container child MainNoteBook.Gtk.Notebook+NotebookChild
			this.GeneralNoteBook1 = new global::Gtk.Notebook ();
			this.GeneralNoteBook1.CanFocus = true;
			this.GeneralNoteBook1.Name = "GeneralNoteBook1";
			this.GeneralNoteBook1.CurrentPage = 0;
			// Container child GeneralNoteBook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			// Container child vbox4.Gtk.Box+BoxChild
			this.LangageLabel = new global::Gtk.Label ();
			this.LangageLabel.Name = "LangageLabel";
			this.LangageLabel.Xpad = 10;
			this.LangageLabel.Xalign = 0F;
			this.LangageLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Langage");
			this.vbox4.Add (this.LangageLabel);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.LangageLabel]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xpad = 10;
			this.hbox8.Add (this.label11);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label11]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.FrenchRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Français"));
			this.FrenchRadioButton.CanFocus = true;
			this.FrenchRadioButton.Name = "FrenchRadioButton";
			this.FrenchRadioButton.Active = true;
			this.FrenchRadioButton.DrawIndicator = true;
			this.FrenchRadioButton.UseUnderline = true;
			this.FrenchRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.hbox8.Add (this.FrenchRadioButton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.FrenchRadioButton]));
			w23.Position = 1;
			w23.Expand = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.EnglishRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("English"));
			this.EnglishRadioButton.CanFocus = true;
			this.EnglishRadioButton.Name = "EnglishRadioButton";
			this.EnglishRadioButton.DrawIndicator = true;
			this.EnglishRadioButton.UseUnderline = true;
			this.EnglishRadioButton.Group = this.FrenchRadioButton.Group;
			this.hbox8.Add (this.EnglishRadioButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.EnglishRadioButton]));
			w24.Position = 2;
			this.hbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.hbox8]));
			w25.Position = 0;
			this.vbox4.Add (this.hbox7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox7]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			this.vbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
			w27.Position = 3;
			this.GeneralNoteBook1.Add (this.vbox4);
			// Notebook tab
			this.InterfaceTab = new global::Gtk.Label ();
			this.InterfaceTab.Name = "InterfaceTab";
			this.InterfaceTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Interface");
			this.GeneralNoteBook1.SetTabLabel (this.vbox4, this.InterfaceTab);
			this.InterfaceTab.ShowAll ();
			// Container child GeneralNoteBook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			// Container child vbox5.Gtk.Box+BoxChild
			this.VariousLabel1 = new global::Gtk.Label ();
			this.VariousLabel1.Name = "VariousLabel1";
			this.VariousLabel1.Xpad = 10;
			this.VariousLabel1.Xalign = 0F;
			this.VariousLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Various");
			this.vbox5.Add (this.VariousLabel1);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.VariousLabel1]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			this.vbox5.Add (this.hbox10);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox10]));
			w30.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			this.vbox5.Add (this.hbox11);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox11]));
			w31.Position = 2;
			this.GeneralNoteBook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w32 = ((global::Gtk.Notebook.NotebookChild)(this.GeneralNoteBook1 [this.vbox5]));
			w32.Position = 1;
			// Notebook tab
			this.OngletTab = new global::Gtk.Label ();
			this.OngletTab.Name = "OngletTab";
			this.OngletTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Various");
			this.GeneralNoteBook1.SetTabLabel (this.vbox5, this.OngletTab);
			this.OngletTab.ShowAll ();
			this.MainNoteBook.Add (this.GeneralNoteBook1);
			global::Gtk.Notebook.NotebookChild w33 = ((global::Gtk.Notebook.NotebookChild)(this.MainNoteBook [this.GeneralNoteBook1]));
			w33.Position = 1;
			// Notebook tab
			this.InterfaceLabelTab = new global::Gtk.Label ();
			this.InterfaceLabelTab.Name = "InterfaceLabelTab";
			this.InterfaceLabelTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Interface");
			this.MainNoteBook.SetTabLabel (this.GeneralNoteBook1, this.InterfaceLabelTab);
			this.InterfaceLabelTab.ShowAll ();
			// Container child MainNoteBook.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			// Container child vbox6.Gtk.Box+BoxChild
			this.LIGDefaultValueLabel = new global::Gtk.Label ();
			this.LIGDefaultValueLabel.Name = "LIGDefaultValueLabel";
			this.LIGDefaultValueLabel.Xpad = 10;
			this.LIGDefaultValueLabel.Xalign = 0F;
			this.LIGDefaultValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Lighting default value :");
			this.vbox6.Add (this.LIGDefaultValueLabel);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LIGDefaultValueLabel]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xpad = 10;
			this.hbox13.Add (this.label12);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label12]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.DefaultValueLabel = new global::Gtk.Label ();
			this.DefaultValueLabel.Name = "DefaultValueLabel";
			this.DefaultValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Default Value :");
			this.hbox13.Add (this.DefaultValueLabel);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.DefaultValueLabel]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.SpinButtonDefaultValue = new global::Gtk.SpinButton (0, 100, 1);
			this.SpinButtonDefaultValue.CanFocus = true;
			this.SpinButtonDefaultValue.Name = "SpinButtonDefaultValue";
			this.SpinButtonDefaultValue.Adjustment.PageIncrement = 10;
			this.SpinButtonDefaultValue.ClimbRate = 1;
			this.SpinButtonDefaultValue.Numeric = true;
			this.hbox13.Add (this.SpinButtonDefaultValue);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.SpinButtonDefaultValue]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.hbox12.Add (this.hbox13);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.hbox13]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox6.Add (this.hbox12);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox12]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xpad = 10;
			this.hbox14.Add (this.label13);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label13]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.FadeLabel = new global::Gtk.Label ();
			this.FadeLabel.Name = "FadeLabel";
			this.FadeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Fade :");
			this.hbox14.Add (this.FadeLabel);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.FadeLabel]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.SpinButtonFade = new global::Gtk.SpinButton (0, 100, 1);
			this.SpinButtonFade.CanFocus = true;
			this.SpinButtonFade.Name = "SpinButtonFade";
			this.SpinButtonFade.Adjustment.PageIncrement = 10;
			this.SpinButtonFade.ClimbRate = 1;
			this.SpinButtonFade.Numeric = true;
			this.hbox14.Add (this.SpinButtonFade);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.SpinButtonFade]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox6.Add (this.hbox14);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox14]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.LIGActionLabel = new global::Gtk.Label ();
			this.LIGActionLabel.Name = "LIGActionLabel";
			this.LIGActionLabel.Xpad = 10;
			this.LIGActionLabel.Xalign = 0F;
			this.LIGActionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Lighting actions name :");
			this.vbox6.Add (this.LIGActionLabel);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.LIGActionLabel]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			w44.Padding = ((uint)(4));
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xpad = 10;
			this.hbox22.Add (this.label18);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.label18]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.LIGToogleLabel = new global::Gtk.Label ();
			this.LIGToogleLabel.Name = "LIGToogleLabel";
			this.LIGToogleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Toggle action :");
			this.hbox22.Add (this.LIGToogleLabel);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.LIGToogleLabel]));
			w46.Position = 1;
			w46.Expand = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.LIGEntryToggle = new global::Gtk.Entry ();
			this.LIGEntryToggle.CanFocus = true;
			this.LIGEntryToggle.Name = "LIGEntryToggle";
			this.LIGEntryToggle.IsEditable = true;
			this.LIGEntryToggle.InvisibleChar = '●';
			this.hbox22.Add (this.LIGEntryToggle);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox22 [this.LIGEntryToggle]));
			w47.Position = 2;
			this.hbox21.Add (this.hbox22);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox21 [this.hbox22]));
			w48.Position = 0;
			this.vbox6.Add (this.hbox21);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox21]));
			w49.Position = 4;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.Xpad = 10;
			this.hbox24.Add (this.label19);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.label19]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.LIGTuneLabel = new global::Gtk.Label ();
			this.LIGTuneLabel.Name = "LIGTuneLabel";
			this.LIGTuneLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Tune action :");
			this.hbox24.Add (this.LIGTuneLabel);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.LIGTuneLabel]));
			w51.Position = 1;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox24.Gtk.Box+BoxChild
			this.LIGEntryTune = new global::Gtk.Entry ();
			this.LIGEntryTune.CanFocus = true;
			this.LIGEntryTune.Name = "LIGEntryTune";
			this.LIGEntryTune.IsEditable = true;
			this.LIGEntryTune.InvisibleChar = '●';
			this.hbox24.Add (this.LIGEntryTune);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox24 [this.LIGEntryTune]));
			w52.Position = 2;
			this.hbox23.Add (this.hbox24);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox23 [this.hbox24]));
			w53.Position = 0;
			this.vbox6.Add (this.hbox23);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox23]));
			w54.Position = 5;
			w54.Expand = false;
			w54.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox25 = new global::Gtk.HBox ();
			this.hbox25.Name = "hbox25";
			this.hbox25.Spacing = 6;
			// Container child hbox25.Gtk.Box+BoxChild
			this.hbox26 = new global::Gtk.HBox ();
			this.hbox26.Name = "hbox26";
			this.hbox26.Spacing = 6;
			// Container child hbox26.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label ();
			this.label20.Name = "label20";
			this.label20.Xpad = 10;
			this.hbox26.Add (this.label20);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.label20]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.LIGStopTuneLabel = new global::Gtk.Label ();
			this.LIGStopTuneLabel.Name = "LIGStopTuneLabel";
			this.LIGStopTuneLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Stop Action :");
			this.hbox26.Add (this.LIGStopTuneLabel);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.LIGStopTuneLabel]));
			w56.Position = 1;
			w56.Expand = false;
			w56.Fill = false;
			// Container child hbox26.Gtk.Box+BoxChild
			this.LIGEntryStop = new global::Gtk.Entry ();
			this.LIGEntryStop.CanFocus = true;
			this.LIGEntryStop.Name = "LIGEntryStop";
			this.LIGEntryStop.IsEditable = true;
			this.LIGEntryStop.InvisibleChar = '●';
			this.hbox26.Add (this.LIGEntryStop);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox26 [this.LIGEntryStop]));
			w57.Position = 2;
			this.hbox25.Add (this.hbox26);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox25 [this.hbox26]));
			w58.Position = 0;
			this.vbox6.Add (this.hbox25);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox25]));
			w59.Position = 6;
			w59.Expand = false;
			w59.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox39 = new global::Gtk.HBox ();
			this.hbox39.Name = "hbox39";
			this.hbox39.Spacing = 6;
			// Container child hbox39.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label ();
			this.label33.Name = "label33";
			this.label33.Xpad = 10;
			this.hbox39.Add (this.label33);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox39 [this.label33]));
			w60.Position = 0;
			w60.Expand = false;
			w60.Fill = false;
			// Container child hbox39.Gtk.Box+BoxChild
			this.LIGSetValueLabel = new global::Gtk.Label ();
			this.LIGSetValueLabel.Name = "LIGSetValueLabel";
			this.LIGSetValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Set Value Action :");
			this.hbox39.Add (this.LIGSetValueLabel);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox39 [this.LIGSetValueLabel]));
			w61.Position = 1;
			w61.Expand = false;
			w61.Fill = false;
			// Container child hbox39.Gtk.Box+BoxChild
			this.LIGEntrySetValue = new global::Gtk.Entry ();
			this.LIGEntrySetValue.CanFocus = true;
			this.LIGEntrySetValue.Name = "LIGEntrySetValue";
			this.LIGEntrySetValue.IsEditable = true;
			this.LIGEntrySetValue.InvisibleChar = '●';
			this.hbox39.Add (this.LIGEntrySetValue);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox39 [this.LIGEntrySetValue]));
			w62.Position = 2;
			this.vbox6.Add (this.hbox39);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox39]));
			w63.Position = 7;
			w63.Expand = false;
			w63.Fill = false;
			this.MainNoteBook.Add (this.vbox6);
			global::Gtk.Notebook.NotebookChild w64 = ((global::Gtk.Notebook.NotebookChild)(this.MainNoteBook [this.vbox6]));
			w64.Position = 2;
			// Notebook tab
			this.LightingLabelTab = new global::Gtk.Label ();
			this.LightingLabelTab.Name = "LightingLabelTab";
			this.LightingLabelTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Lighting");
			this.MainNoteBook.SetTabLabel (this.vbox6, this.LightingLabelTab);
			this.LightingLabelTab.ShowAll ();
			// Container child MainNoteBook.Gtk.Notebook+NotebookChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			// Container child vbox7.Gtk.Box+BoxChild
			this.SWIDefaultValueLabel = new global::Gtk.Label ();
			this.SWIDefaultValueLabel.Name = "SWIDefaultValueLabel";
			this.SWIDefaultValueLabel.Xpad = 10;
			this.SWIDefaultValueLabel.Xalign = 0F;
			this.SWIDefaultValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Switch default value :");
			this.vbox7.Add (this.SWIDefaultValueLabel);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.SWIDefaultValueLabel]));
			w65.Position = 0;
			w65.Expand = false;
			w65.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xpad = 10;
			this.hbox16.Add (this.label14);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.label14]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.InverseLabel = new global::Gtk.Label ();
			this.InverseLabel.Name = "InverseLabel";
			this.InverseLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Inverse :");
			this.hbox16.Add (this.InverseLabel);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.InverseLabel]));
			w67.Position = 1;
			w67.Expand = false;
			w67.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.CheckButtonInverse = new global::Gtk.CheckButton ();
			this.CheckButtonInverse.CanFocus = true;
			this.CheckButtonInverse.Name = "CheckButtonInverse";
			this.CheckButtonInverse.Label = "";
			this.CheckButtonInverse.DrawIndicator = true;
			this.CheckButtonInverse.UseUnderline = true;
			this.hbox16.Add (this.CheckButtonInverse);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox16 [this.CheckButtonInverse]));
			w68.Position = 2;
			this.hbox15.Add (this.hbox16);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.hbox16]));
			w69.Position = 0;
			this.vbox7.Add (this.hbox15);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox15]));
			w70.Position = 1;
			w70.Expand = false;
			w70.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xpad = 10;
			this.hbox17.Add (this.label15);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.label15]));
			w71.Position = 0;
			w71.Expand = false;
			w71.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.ImpulstionTimeLabel = new global::Gtk.Label ();
			this.ImpulstionTimeLabel.Name = "ImpulstionTimeLabel";
			this.ImpulstionTimeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Impulsion Time :");
			this.hbox17.Add (this.ImpulstionTimeLabel);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.ImpulstionTimeLabel]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			// Container child hbox17.Gtk.Box+BoxChild
			this.SpinButtonImpulsionTime = new global::Gtk.SpinButton (0, 100, 1);
			this.SpinButtonImpulsionTime.CanFocus = true;
			this.SpinButtonImpulsionTime.Name = "SpinButtonImpulsionTime";
			this.SpinButtonImpulsionTime.Adjustment.PageIncrement = 10;
			this.SpinButtonImpulsionTime.ClimbRate = 1;
			this.SpinButtonImpulsionTime.Numeric = true;
			this.hbox17.Add (this.SpinButtonImpulsionTime);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox17 [this.SpinButtonImpulsionTime]));
			w73.Position = 2;
			w73.Expand = false;
			w73.Fill = false;
			this.vbox7.Add (this.hbox17);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox17]));
			w74.Position = 2;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.SWIActionLabel = new global::Gtk.Label ();
			this.SWIActionLabel.Name = "SWIActionLabel";
			this.SWIActionLabel.Xpad = 10;
			this.SWIActionLabel.Xalign = 0F;
			this.SWIActionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Switch actions name :");
			this.vbox7.Add (this.SWIActionLabel);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.SWIActionLabel]));
			w75.Position = 3;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox27 = new global::Gtk.HBox ();
			this.hbox27.Name = "hbox27";
			this.hbox27.Spacing = 6;
			// Container child hbox27.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label ();
			this.label21.Name = "label21";
			this.label21.Xpad = 10;
			this.hbox27.Add (this.label21);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.label21]));
			w76.Position = 0;
			w76.Expand = false;
			w76.Fill = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.SWIClicLabel = new global::Gtk.Label ();
			this.SWIClicLabel.Name = "SWIClicLabel";
			this.SWIClicLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Clic action :");
			this.hbox27.Add (this.SWIClicLabel);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.SWIClicLabel]));
			w77.Position = 1;
			w77.Expand = false;
			// Container child hbox27.Gtk.Box+BoxChild
			this.SWIEntryClic = new global::Gtk.Entry ();
			this.SWIEntryClic.CanFocus = true;
			this.SWIEntryClic.Name = "SWIEntryClic";
			this.SWIEntryClic.IsEditable = true;
			this.SWIEntryClic.InvisibleChar = '●';
			this.hbox27.Add (this.SWIEntryClic);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox27 [this.SWIEntryClic]));
			w78.Position = 2;
			this.vbox7.Add (this.hbox27);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox27]));
			w79.Position = 4;
			w79.Expand = false;
			w79.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox28 = new global::Gtk.HBox ();
			this.hbox28.Name = "hbox28";
			this.hbox28.Spacing = 6;
			// Container child hbox28.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label ();
			this.label22.Name = "label22";
			this.label22.Xpad = 10;
			this.hbox28.Add (this.label22);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.label22]));
			w80.Position = 0;
			w80.Expand = false;
			w80.Fill = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.SWIDoubleClicLabel = new global::Gtk.Label ();
			this.SWIDoubleClicLabel.Name = "SWIDoubleClicLabel";
			this.SWIDoubleClicLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Double clic action :");
			this.hbox28.Add (this.SWIDoubleClicLabel);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.SWIDoubleClicLabel]));
			w81.Position = 1;
			w81.Expand = false;
			// Container child hbox28.Gtk.Box+BoxChild
			this.SWIEntryDoubleClic = new global::Gtk.Entry ();
			this.SWIEntryDoubleClic.CanFocus = true;
			this.SWIEntryDoubleClic.Name = "SWIEntryDoubleClic";
			this.SWIEntryDoubleClic.IsEditable = true;
			this.SWIEntryDoubleClic.InvisibleChar = '●';
			this.hbox28.Add (this.SWIEntryDoubleClic);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.hbox28 [this.SWIEntryDoubleClic]));
			w82.Position = 2;
			this.vbox7.Add (this.hbox28);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox28]));
			w83.Position = 5;
			w83.Expand = false;
			w83.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox29 = new global::Gtk.HBox ();
			this.hbox29.Name = "hbox29";
			this.hbox29.Spacing = 6;
			// Container child hbox29.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label ();
			this.label23.Name = "label23";
			this.label23.Xpad = 10;
			this.hbox29.Add (this.label23);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox29 [this.label23]));
			w84.Position = 0;
			w84.Expand = false;
			w84.Fill = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.SWIOnLabel = new global::Gtk.Label ();
			this.SWIOnLabel.Name = "SWIOnLabel";
			this.SWIOnLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("On action :");
			this.hbox29.Add (this.SWIOnLabel);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox29 [this.SWIOnLabel]));
			w85.Position = 1;
			w85.Expand = false;
			// Container child hbox29.Gtk.Box+BoxChild
			this.SWIEntryOn = new global::Gtk.Entry ();
			this.SWIEntryOn.CanFocus = true;
			this.SWIEntryOn.Name = "SWIEntryOn";
			this.SWIEntryOn.IsEditable = true;
			this.SWIEntryOn.InvisibleChar = '●';
			this.hbox29.Add (this.SWIEntryOn);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox29 [this.SWIEntryOn]));
			w86.Position = 2;
			this.vbox7.Add (this.hbox29);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox29]));
			w87.Position = 6;
			w87.Expand = false;
			w87.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox30 = new global::Gtk.HBox ();
			this.hbox30.Name = "hbox30";
			this.hbox30.Spacing = 6;
			// Container child hbox30.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xpad = 10;
			this.hbox30.Add (this.label24);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox30 [this.label24]));
			w88.Position = 0;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.SWIOnFmLabel = new global::Gtk.Label ();
			this.SWIOnFmLabel.Name = "SWIOnFmLabel";
			this.SWIOnFmLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Rising action :");
			this.hbox30.Add (this.SWIOnFmLabel);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox30 [this.SWIOnFmLabel]));
			w89.Position = 1;
			w89.Expand = false;
			// Container child hbox30.Gtk.Box+BoxChild
			this.SWIEntryOnFm = new global::Gtk.Entry ();
			this.SWIEntryOnFm.CanFocus = true;
			this.SWIEntryOnFm.Name = "SWIEntryOnFm";
			this.SWIEntryOnFm.IsEditable = true;
			this.SWIEntryOnFm.InvisibleChar = '●';
			this.hbox30.Add (this.SWIEntryOnFm);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.hbox30 [this.SWIEntryOnFm]));
			w90.Position = 2;
			this.vbox7.Add (this.hbox30);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox30]));
			w91.Position = 7;
			w91.Expand = false;
			w91.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox31 = new global::Gtk.HBox ();
			this.hbox31.Name = "hbox31";
			this.hbox31.Spacing = 6;
			// Container child hbox31.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label ();
			this.label25.Name = "label25";
			this.label25.Xpad = 10;
			this.hbox31.Add (this.label25);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.label25]));
			w92.Position = 0;
			w92.Expand = false;
			w92.Fill = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.SWIOffLabel = new global::Gtk.Label ();
			this.SWIOffLabel.Name = "SWIOffLabel";
			this.SWIOffLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Off action :");
			this.hbox31.Add (this.SWIOffLabel);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.SWIOffLabel]));
			w93.Position = 1;
			w93.Expand = false;
			// Container child hbox31.Gtk.Box+BoxChild
			this.SWIEntryOff = new global::Gtk.Entry ();
			this.SWIEntryOff.CanFocus = true;
			this.SWIEntryOff.Name = "SWIEntryOff";
			this.SWIEntryOff.IsEditable = true;
			this.SWIEntryOff.InvisibleChar = '●';
			this.hbox31.Add (this.SWIEntryOff);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox31 [this.SWIEntryOff]));
			w94.Position = 2;
			this.vbox7.Add (this.hbox31);
			global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox31]));
			w95.Position = 8;
			w95.Expand = false;
			w95.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox32 = new global::Gtk.HBox ();
			this.hbox32.Name = "hbox32";
			this.hbox32.Spacing = 6;
			// Container child hbox32.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label ();
			this.label26.Name = "label26";
			this.label26.Xpad = 10;
			this.hbox32.Add (this.label26);
			global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.hbox32 [this.label26]));
			w96.Position = 0;
			w96.Expand = false;
			w96.Fill = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.SWIOffFmLabel = new global::Gtk.Label ();
			this.SWIOffFmLabel.Name = "SWIOffFmLabel";
			this.SWIOffFmLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Failing action :");
			this.hbox32.Add (this.SWIOffFmLabel);
			global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.hbox32 [this.SWIOffFmLabel]));
			w97.Position = 1;
			w97.Expand = false;
			// Container child hbox32.Gtk.Box+BoxChild
			this.SWIEntryOffFm = new global::Gtk.Entry ();
			this.SWIEntryOffFm.CanFocus = true;
			this.SWIEntryOffFm.Name = "SWIEntryOffFm";
			this.SWIEntryOffFm.IsEditable = true;
			this.SWIEntryOffFm.InvisibleChar = '●';
			this.hbox32.Add (this.SWIEntryOffFm);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox32 [this.SWIEntryOffFm]));
			w98.Position = 2;
			this.vbox7.Add (this.hbox32);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox32]));
			w99.Position = 9;
			w99.Expand = false;
			w99.Fill = false;
			this.MainNoteBook.Add (this.vbox7);
			global::Gtk.Notebook.NotebookChild w100 = ((global::Gtk.Notebook.NotebookChild)(this.MainNoteBook [this.vbox7]));
			w100.Position = 3;
			// Notebook tab
			this.SwitchLabelTab = new global::Gtk.Label ();
			this.SwitchLabelTab.Name = "SwitchLabelTab";
			this.SwitchLabelTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Switch");
			this.MainNoteBook.SetTabLabel (this.vbox7, this.SwitchLabelTab);
			this.SwitchLabelTab.ShowAll ();
			// Container child MainNoteBook.Gtk.Notebook+NotebookChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			// Container child vbox8.Gtk.Box+BoxChild
			this.SHUDefaultValueLabel = new global::Gtk.Label ();
			this.SHUDefaultValueLabel.Name = "SHUDefaultValueLabel";
			this.SHUDefaultValueLabel.Xpad = 10;
			this.SHUDefaultValueLabel.Xalign = 0F;
			this.SHUDefaultValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Shutter default value :");
			this.vbox8.Add (this.SHUDefaultValueLabel);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.SHUDefaultValueLabel]));
			w101.Position = 0;
			w101.Expand = false;
			w101.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xpad = 10;
			this.hbox19.Add (this.label16);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.label16]));
			w102.Position = 0;
			w102.Expand = false;
			w102.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.ShutterTypeLabel = new global::Gtk.Label ();
			this.ShutterTypeLabel.Name = "ShutterTypeLabel";
			this.ShutterTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Shutter type :");
			this.hbox19.Add (this.ShutterTypeLabel);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.ShutterTypeLabel]));
			w103.Position = 1;
			w103.Expand = false;
			w103.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.ComboboxShutterType = global::Gtk.ComboBox.NewText ();
			this.ComboboxShutterType.Name = "ComboboxShutterType";
			this.hbox19.Add (this.ComboboxShutterType);
			global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.hbox19 [this.ComboboxShutterType]));
			w104.Position = 2;
			w104.Expand = false;
			w104.Fill = false;
			this.hbox18.Add (this.hbox19);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.hbox18 [this.hbox19]));
			w105.Position = 0;
			w105.Expand = false;
			w105.Fill = false;
			this.vbox8.Add (this.hbox18);
			global::Gtk.Box.BoxChild w106 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox18]));
			w106.Position = 1;
			w106.Expand = false;
			w106.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.Xpad = 10;
			this.hbox20.Add (this.label17);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.label17]));
			w107.Position = 0;
			w107.Expand = false;
			w107.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.TravelTimeLabel = new global::Gtk.Label ();
			this.TravelTimeLabel.Name = "TravelTimeLabel";
			this.TravelTimeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Travel Time :");
			this.hbox20.Add (this.TravelTimeLabel);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.TravelTimeLabel]));
			w108.Position = 1;
			w108.Expand = false;
			w108.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.SpinButtonTravelTime = new global::Gtk.SpinButton (0, 1000, 1);
			this.SpinButtonTravelTime.CanFocus = true;
			this.SpinButtonTravelTime.Name = "SpinButtonTravelTime";
			this.SpinButtonTravelTime.Adjustment.PageIncrement = 10;
			this.SpinButtonTravelTime.ClimbRate = 1;
			this.SpinButtonTravelTime.Numeric = true;
			this.hbox20.Add (this.SpinButtonTravelTime);
			global::Gtk.Box.BoxChild w109 = ((global::Gtk.Box.BoxChild)(this.hbox20 [this.SpinButtonTravelTime]));
			w109.Position = 2;
			w109.Expand = false;
			w109.Fill = false;
			this.vbox8.Add (this.hbox20);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox20]));
			w110.Position = 2;
			w110.Expand = false;
			w110.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox36 = new global::Gtk.HBox ();
			this.hbox36.Name = "hbox36";
			this.hbox36.Spacing = 6;
			// Container child hbox36.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label ();
			this.label30.Name = "label30";
			this.label30.Xpad = 10;
			this.hbox36.Add (this.label30);
			global::Gtk.Box.BoxChild w111 = ((global::Gtk.Box.BoxChild)(this.hbox36 [this.label30]));
			w111.Position = 0;
			w111.Expand = false;
			w111.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.InitTimeLabel = new global::Gtk.Label ();
			this.InitTimeLabel.Name = "InitTimeLabel";
			this.InitTimeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Init Time :");
			this.hbox36.Add (this.InitTimeLabel);
			global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox36 [this.InitTimeLabel]));
			w112.Position = 1;
			w112.Expand = false;
			w112.Fill = false;
			// Container child hbox36.Gtk.Box+BoxChild
			this.SpinButtonInitTime = new global::Gtk.SpinButton (0, 1000, 1);
			this.SpinButtonInitTime.CanFocus = true;
			this.SpinButtonInitTime.Name = "SpinButtonInitTime";
			this.SpinButtonInitTime.Adjustment.PageIncrement = 10;
			this.SpinButtonInitTime.ClimbRate = 1;
			this.SpinButtonInitTime.Numeric = true;
			this.hbox36.Add (this.SpinButtonInitTime);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox36 [this.SpinButtonInitTime]));
			w113.Position = 2;
			w113.Expand = false;
			w113.Fill = false;
			this.vbox8.Add (this.hbox36);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox36]));
			w114.Position = 3;
			w114.Expand = false;
			w114.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.SHUActionLabel = new global::Gtk.Label ();
			this.SHUActionLabel.Name = "SHUActionLabel";
			this.SHUActionLabel.Xpad = 10;
			this.SHUActionLabel.Xalign = 0F;
			this.SHUActionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Shutter default value :");
			this.vbox8.Add (this.SHUActionLabel);
			global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.SHUActionLabel]));
			w115.Position = 4;
			w115.Expand = false;
			w115.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox33 = new global::Gtk.HBox ();
			this.hbox33.Name = "hbox33";
			this.hbox33.Spacing = 6;
			// Container child hbox33.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label ();
			this.label27.Name = "label27";
			this.label27.Xpad = 10;
			this.hbox33.Add (this.label27);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.label27]));
			w116.Position = 0;
			w116.Expand = false;
			w116.Fill = false;
			// Container child hbox33.Gtk.Box+BoxChild
			this.SHUOpenLabel = new global::Gtk.Label ();
			this.SHUOpenLabel.Name = "SHUOpenLabel";
			this.SHUOpenLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Open action :");
			this.hbox33.Add (this.SHUOpenLabel);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.SHUOpenLabel]));
			w117.Position = 1;
			w117.Expand = false;
			// Container child hbox33.Gtk.Box+BoxChild
			this.SHUEntryOpen = new global::Gtk.Entry ();
			this.SHUEntryOpen.CanFocus = true;
			this.SHUEntryOpen.Name = "SHUEntryOpen";
			this.SHUEntryOpen.IsEditable = true;
			this.SHUEntryOpen.InvisibleChar = '●';
			this.hbox33.Add (this.SHUEntryOpen);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.hbox33 [this.SHUEntryOpen]));
			w118.Position = 2;
			this.vbox8.Add (this.hbox33);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox33]));
			w119.Position = 5;
			w119.Expand = false;
			w119.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox34 = new global::Gtk.HBox ();
			this.hbox34.Name = "hbox34";
			this.hbox34.Spacing = 6;
			// Container child hbox34.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label ();
			this.label28.Name = "label28";
			this.label28.Xpad = 10;
			this.hbox34.Add (this.label28);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.hbox34 [this.label28]));
			w120.Position = 0;
			w120.Expand = false;
			w120.Fill = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.SHUCloseLabel = new global::Gtk.Label ();
			this.SHUCloseLabel.Name = "SHUCloseLabel";
			this.SHUCloseLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Close action :");
			this.hbox34.Add (this.SHUCloseLabel);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox34 [this.SHUCloseLabel]));
			w121.Position = 1;
			w121.Expand = false;
			// Container child hbox34.Gtk.Box+BoxChild
			this.SHUEntryClose = new global::Gtk.Entry ();
			this.SHUEntryClose.CanFocus = true;
			this.SHUEntryClose.Name = "SHUEntryClose";
			this.SHUEntryClose.IsEditable = true;
			this.SHUEntryClose.InvisibleChar = '●';
			this.hbox34.Add (this.SHUEntryClose);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox34 [this.SHUEntryClose]));
			w122.Position = 2;
			this.vbox8.Add (this.hbox34);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox34]));
			w123.Position = 6;
			w123.Expand = false;
			w123.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox35 = new global::Gtk.HBox ();
			this.hbox35.Name = "hbox35";
			this.hbox35.Spacing = 6;
			// Container child hbox35.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label ();
			this.label29.Name = "label29";
			this.label29.Xpad = 10;
			this.hbox35.Add (this.label29);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.hbox35 [this.label29]));
			w124.Position = 0;
			w124.Expand = false;
			w124.Fill = false;
			// Container child hbox35.Gtk.Box+BoxChild
			this.SHUStopLabel = new global::Gtk.Label ();
			this.SHUStopLabel.Name = "SHUStopLabel";
			this.SHUStopLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Stop action :");
			this.hbox35.Add (this.SHUStopLabel);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.hbox35 [this.SHUStopLabel]));
			w125.Position = 1;
			w125.Expand = false;
			// Container child hbox35.Gtk.Box+BoxChild
			this.SHUEntryStop = new global::Gtk.Entry ();
			this.SHUEntryStop.CanFocus = true;
			this.SHUEntryStop.Name = "SHUEntryStop";
			this.SHUEntryStop.IsEditable = true;
			this.SHUEntryStop.InvisibleChar = '●';
			this.hbox35.Add (this.SHUEntryStop);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox35 [this.SHUEntryStop]));
			w126.Position = 2;
			this.vbox8.Add (this.hbox35);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox35]));
			w127.Position = 7;
			w127.Expand = false;
			w127.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox37 = new global::Gtk.HBox ();
			this.hbox37.Name = "hbox37";
			this.hbox37.Spacing = 6;
			// Container child hbox37.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label ();
			this.label31.Name = "label31";
			this.label31.Xpad = 10;
			this.hbox37.Add (this.label31);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.label31]));
			w128.Position = 0;
			w128.Expand = false;
			w128.Fill = false;
			// Container child hbox37.Gtk.Box+BoxChild
			this.SHUToggleLabel = new global::Gtk.Label ();
			this.SHUToggleLabel.Name = "SHUToggleLabel";
			this.SHUToggleLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Toggle action :");
			this.hbox37.Add (this.SHUToggleLabel);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.SHUToggleLabel]));
			w129.Position = 1;
			w129.Expand = false;
			// Container child hbox37.Gtk.Box+BoxChild
			this.SHUEntryToggle = new global::Gtk.Entry ();
			this.SHUEntryToggle.CanFocus = true;
			this.SHUEntryToggle.Name = "SHUEntryToggle";
			this.SHUEntryToggle.IsEditable = true;
			this.SHUEntryToggle.InvisibleChar = '●';
			this.hbox37.Add (this.SHUEntryToggle);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox37 [this.SHUEntryToggle]));
			w130.Position = 2;
			this.vbox8.Add (this.hbox37);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox37]));
			w131.Position = 8;
			w131.Expand = false;
			w131.Fill = false;
			this.MainNoteBook.Add (this.vbox8);
			global::Gtk.Notebook.NotebookChild w132 = ((global::Gtk.Notebook.NotebookChild)(this.MainNoteBook [this.vbox8]));
			w132.Position = 4;
			// Notebook tab
			this.ShutterLabelTab = new global::Gtk.Label ();
			this.ShutterLabelTab.Name = "ShutterLabelTab";
			this.ShutterLabelTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Shutter");
			this.MainNoteBook.SetTabLabel (this.vbox8, this.ShutterLabelTab);
			this.ShutterLabelTab.ShowAll ();
			// Container child MainNoteBook.Gtk.Notebook+NotebookChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.TEMPActionLabel = new global::Gtk.Label ();
			this.TEMPActionLabel.Name = "TEMPActionLabel";
			this.TEMPActionLabel.Xpad = 10;
			this.TEMPActionLabel.Xalign = 0F;
			this.TEMPActionLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Temperature action value :");
			this.vbox9.Add (this.TEMPActionLabel);
			global::Gtk.Box.BoxChild w133 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.TEMPActionLabel]));
			w133.Position = 0;
			w133.Expand = false;
			w133.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox38 = new global::Gtk.HBox ();
			this.hbox38.Name = "hbox38";
			this.hbox38.Spacing = 6;
			// Container child hbox38.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label ();
			this.label32.Name = "label32";
			this.label32.Xpad = 10;
			this.hbox38.Add (this.label32);
			global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.hbox38 [this.label32]));
			w134.Position = 0;
			w134.Expand = false;
			w134.Fill = false;
			// Container child hbox38.Gtk.Box+BoxChild
			this.TEMPGetLabel = new global::Gtk.Label ();
			this.TEMPGetLabel.Name = "TEMPGetLabel";
			this.TEMPGetLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Open action :");
			this.hbox38.Add (this.TEMPGetLabel);
			global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.hbox38 [this.TEMPGetLabel]));
			w135.Position = 1;
			w135.Expand = false;
			// Container child hbox38.Gtk.Box+BoxChild
			this.TEMPEntryGet = new global::Gtk.Entry ();
			this.TEMPEntryGet.CanFocus = true;
			this.TEMPEntryGet.Name = "TEMPEntryGet";
			this.TEMPEntryGet.IsEditable = true;
			this.TEMPEntryGet.InvisibleChar = '●';
			this.hbox38.Add (this.TEMPEntryGet);
			global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.hbox38 [this.TEMPEntryGet]));
			w136.Position = 2;
			this.vbox9.Add (this.hbox38);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.hbox38]));
			w137.Position = 1;
			w137.Expand = false;
			w137.Fill = false;
			this.MainNoteBook.Add (this.vbox9);
			global::Gtk.Notebook.NotebookChild w138 = ((global::Gtk.Notebook.NotebookChild)(this.MainNoteBook [this.vbox9]));
			w138.Position = 5;
			// Notebook tab
			this.TemperatureLabelTab = new global::Gtk.Label ();
			this.TemperatureLabelTab.Name = "TemperatureLabelTab";
			this.TemperatureLabelTab.LabelProp = global::Mono.Unix.Catalog.GetString ("Temperature");
			this.MainNoteBook.SetTabLabel (this.vbox9, this.TemperatureLabelTab);
			this.TemperatureLabelTab.ShowAll ();
			w1.Add (this.MainNoteBook);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(w1 [this.MainNoteBook]));
			w139.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.ErrorLabel = new global::Gtk.Label ();
			this.ErrorLabel.Name = "ErrorLabel";
			this.ErrorLabel.Yalign = 0F;
			w1.Add (this.ErrorLabel);
			global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(w1 [this.ErrorLabel]));
			w140.Position = 1;
			w140.Expand = false;
			w140.Fill = false;
			// Internal child xPLduinoManager.ChangePreferences.ActionArea
			global::Gtk.HButtonBox w141 = this.ActionArea;
			w141.Name = "dialog1_ActionArea";
			w141.Spacing = 10;
			w141.BorderWidth = ((uint)(5));
			w141.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w142 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w141 [this.buttonCancel]));
			w142.Expand = false;
			w142.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w143 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w141 [this.buttonOk]));
			w143.Position = 1;
			w143.Expand = false;
			w143.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 658;
			this.DefaultHeight = 552;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.LIGEntryToggle.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnEntryToggleFocusOutEvent);
			this.LIGEntryTune.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnEntryTuneFocusOutEvent);
			this.LIGEntryStop.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnEntryStopFocusOutEvent);
			this.LIGEntrySetValue.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnEntryStopFocusOutEvent);
			this.SWIEntryClic.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSWIEntryClicFocusOutEvent);
			this.SWIEntryDoubleClic.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSWIEntryDoubleClicFocusOutEvent);
			this.SWIEntryOn.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSWIEntryOnFocusOutEvent);
			this.SWIEntryOnFm.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSWIEntryOnFmFocusOutEvent);
			this.SWIEntryOff.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSWIEntryOffFocusOutEvent);
			this.SWIEntryOffFm.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSWIEntryOffFmFocusOutEvent);
			this.SHUEntryOpen.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSHUEntryOpenFocusOutEvent);
			this.SHUEntryClose.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSHUEntryCloseFocusOutEvent);
			this.SHUEntryStop.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSHUEntryStopFocusOutEvent);
			this.SHUEntryToggle.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSHUEntryToggleFocusOutEvent);
			this.TEMPEntryGet.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnTEMPEntryGetFocusOutEvent);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
