
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class Welcome
	{
		private global::Gtk.VBox vbox6;
		private global::Gtk.Image image71;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.Welcome
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xPLduinoManager.Welcome";
			// Container child xPLduinoManager.Welcome.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image71 = new global::Gtk.Image ();
			this.image71.Name = "image71";
			this.image71.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("xPLduinoManager.Pictures.xplduino-FirstPage.png");
			this.vbox6.Add (this.image71);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.image71]));
			w1.Position = 0;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
