
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action FileAction;
		private global::Gtk.Action newAction;
		private global::Gtk.Action openAction;
		private global::Gtk.Action CreateConfigurationAction;
		private global::Gtk.Action ToolsAction;
		private global::Gtk.Action FentreAction;
		private global::Gtk.Action goForwardAction;
		private global::Gtk.Action goBackAction;
		private global::Gtk.Action closeAction;
		private global::Gtk.Action quitAction;
		private global::Gtk.Action EditAction;
		private global::Gtk.Action undoAction;
		private global::Gtk.Action redoAction;
		private global::Gtk.Action MyPreferenceAction;
		private global::Gtk.Action saveAction;
		private global::Gtk.Action saveAsAction;
		private global::Gtk.Action ExtractEmbeddedAction;
		private global::Gtk.Action LoadEmbeddedAction;
		private global::Gtk.Action HelpAction;
		private global::Gtk.Action aboutAction;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Button ButtonNewProject;
		private global::Gtk.Button ButtonOpenProject;
		private global::Gtk.Button ButtonSaveProject;
		private global::Gtk.Button ButtonSaveAllProject;
		private global::Gtk.VSeparator vseparator1;
		private global::Gtk.Button UndoButton;
		private global::Gtk.Button RedoButton;
		private global::Gtk.VSeparator vseparator2;
		private global::Gtk.ComboBox ComboboxSelectNode;
		private global::Gtk.Button ButtonCheckEmbedded;
		private global::Gtk.VSeparator vseparator5;
		private global::Gtk.Button ButtonReloadUSB;
		private global::Gtk.ComboBox ComboboxSelectUsb;
		private global::Gtk.Button ButtonLoadEmbedded;
		private global::Gtk.VSeparator vseparator4;
		private global::Gtk.Button ButtonReadEthernet;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.HPaned hpaned1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.EventBox eventbox9;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Label LabelTreeView;
		private global::Gtk.Button Up;
		private global::Gtk.Button Down;
		private global::Gtk.Button Reduce;
		private global::Gtk.Button Expand;
		private global::Gtk.HBox hbox2;
		private global::Gtk.ScrolledWindow scrolledwindow1;
		private global::Gtk.TreeView ExplorerTreeView;
		private global::Gtk.VBox VBoxButtonNews;
		private global::Gtk.Label LabelButton;
		private global::Gtk.Button ButtonNew3;
		private global::Gtk.Button ButtonNew2;
		private global::Gtk.Button ButtonNew1;
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.HPaned hpaned2;
		private global::Gtk.ScrolledWindow scrolledwindow2;
		private global::Gtk.Notebook MainNoteBook;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::Gtk.Notebook SecondNoteBook;
		private global::Gtk.Notebook ViewNoteBook;
		private global::Gtk.VBox vbox4;
		private global::Gtk.EventBox eventbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label LabelInformation;
		private global::Gtk.ToggleButton ButtonFilterInfo;
		private global::Gtk.ToggleButton ButtonFilterWarning;
		private global::Gtk.ToggleButton ButtonFilterError;
		private global::Gtk.ToggleButton ButtonFilterQuestion;
		private global::Gtk.Button EraseOutput;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView OutputTreeview;
		private global::Gtk.Label OutputTab;
		private global::Gtk.VBox vbox5;
		private global::Gtk.EventBox eventbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label LabelHistoric;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView HistoricTreeView;
		private global::Gtk.Label HistoryTab;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label LabelInfoProject;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.Label LabelPathProject;
		private global::Gtk.ProgressBar ProgressBar;
		private global::Gtk.Button ExpendHistoryPanel;
		private global::Gtk.Button ReduceHistoryPanel;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New Project"), null, "gtk-new");
			this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Project");
			w1.Add (this.newAction, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open Project"), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Project");
			w1.Add (this.openAction, null);
			this.CreateConfigurationAction = new global::Gtk.Action ("CreateConfigurationAction", global::Mono.Unix.Catalog.GetString ("Create Configuration"), null, null);
			this.CreateConfigurationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create Configuration");
			w1.Add (this.CreateConfigurationAction, "<Primary><Mod2>w");
			this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
			w1.Add (this.ToolsAction, null);
			this.FentreAction = new global::Gtk.Action ("FentreAction", global::Mono.Unix.Catalog.GetString ("Fenêtre"), null, null);
			this.FentreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fenêtre");
			w1.Add (this.FentreAction, null);
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", global::Mono.Unix.Catalog.GetString ("Fenêtre suivante"), null, "gtk-go-forward");
			this.goForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fenêtre suivante");
			w1.Add (this.goForwardAction, "<Primary><Mod2>Page_Up");
			this.goBackAction = new global::Gtk.Action ("goBackAction", global::Mono.Unix.Catalog.GetString ("Fenêtre précédente"), null, "gtk-go-back");
			this.goBackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fenêtre précédente");
			w1.Add (this.goBackAction, "<Primary><Mod2>Page_Down");
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Tout fermer"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tout fermer");
			w1.Add (this.closeAction, "<Primary><Alt><Mod2>w");
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.quitAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("Undo"), null, "gtk-undo");
			this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Undo");
			w1.Add (this.undoAction, "<Primary><Mod2>z");
			this.redoAction = new global::Gtk.Action ("redoAction", global::Mono.Unix.Catalog.GetString ("Redo"), null, "gtk-redo");
			this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Redo");
			w1.Add (this.redoAction, "<Primary><Mod2>y");
			this.MyPreferenceAction = new global::Gtk.Action ("MyPreferenceAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, "gtk-preferences");
			this.MyPreferenceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.MyPreferenceAction, "<Primary><Alt><Mod2>p");
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
			w1.Add (this.saveAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save All"), null, "gtk-save-as");
			this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save All");
			w1.Add (this.saveAsAction, "<Primary><Mod2>d");
			this.ExtractEmbeddedAction = new global::Gtk.Action ("ExtractEmbeddedAction", global::Mono.Unix.Catalog.GetString ("Verify Embedded"), null, "gtk-ok");
			this.ExtractEmbeddedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Verify Embedded");
			w1.Add (this.ExtractEmbeddedAction, "<Primary><Mod2>r");
			this.LoadEmbeddedAction = new global::Gtk.Action ("LoadEmbeddedAction", global::Mono.Unix.Catalog.GetString ("Load Embedded"), null, "gtk-media-play");
			this.LoadEmbeddedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Load Embedded");
			w1.Add (this.LoadEmbeddedAction, null);
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "xPLduinoManager.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("xPLduino - Manager");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("xPLduinoManager.Pictures.Project.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child xPLduinoManager.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><separator/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='CreateConfigurationAction' action='CreateConfigurationAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='undoAction' action='undoAction'/><menuitem name='redoAction' action='redoAction'/><separator/><menuitem name='MyPreferenceAction' action='MyPreferenceAction'/></menu><menu name='ToolsAction' action='ToolsAction'><menuitem name='ExtractEmbeddedAction' action='ExtractEmbeddedAction'/><menuitem name='LoadEmbeddedAction' action='LoadEmbeddedAction'/></menu><menu name='FentreAction' action='FentreAction'><menuitem name='goForwardAction' action='goForwardAction'/><menuitem name='goBackAction' action='goBackAction'/><separator/><menuitem name='closeAction' action='closeAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonNewProject = new global::Gtk.Button ();
			this.ButtonNewProject.Name = "ButtonNewProject";
			this.ButtonNewProject.UseUnderline = true;
			this.ButtonNewProject.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonNewProject.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w4.Add (w7);
			w3.Add (w4);
			this.ButtonNewProject.Add (w3);
			this.hbox7.Add (this.ButtonNewProject);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonNewProject]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonOpenProject = new global::Gtk.Button ();
			this.ButtonOpenProject.Name = "ButtonOpenProject";
			this.ButtonOpenProject.UseUnderline = true;
			this.ButtonOpenProject.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonOpenProject.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w13.Add (w16);
			w12.Add (w13);
			this.ButtonOpenProject.Add (w12);
			this.hbox7.Add (this.ButtonOpenProject);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonOpenProject]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonSaveProject = new global::Gtk.Button ();
			this.ButtonSaveProject.Name = "ButtonSaveProject";
			this.ButtonSaveProject.UseUnderline = true;
			this.ButtonSaveProject.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonSaveProject.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w22.Add (w25);
			w21.Add (w22);
			this.ButtonSaveProject.Add (w21);
			this.hbox7.Add (this.ButtonSaveProject);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonSaveProject]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonSaveAllProject = new global::Gtk.Button ();
			this.ButtonSaveAllProject.Name = "ButtonSaveAllProject";
			this.ButtonSaveAllProject.UseUnderline = true;
			this.ButtonSaveAllProject.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonSaveAllProject.Gtk.Container+ContainerChild
			global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w31 = new global::Gtk.HBox ();
			w31.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			w31.Add (w32);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w34 = new global::Gtk.Label ();
			w31.Add (w34);
			w30.Add (w31);
			this.ButtonSaveAllProject.Add (w30);
			this.hbox7.Add (this.ButtonSaveAllProject);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonSaveAllProject]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox7.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator1]));
			w39.Position = 4;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.UndoButton = new global::Gtk.Button ();
			this.UndoButton.CanFocus = true;
			this.UndoButton.Name = "UndoButton";
			this.UndoButton.UseUnderline = true;
			this.UndoButton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child UndoButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w40 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w41 = new global::Gtk.HBox ();
			w41.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w42 = new global::Gtk.Image ();
			w42.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-undo", global::Gtk.IconSize.Menu);
			w41.Add (w42);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w44 = new global::Gtk.Label ();
			w41.Add (w44);
			w40.Add (w41);
			this.UndoButton.Add (w40);
			this.hbox7.Add (this.UndoButton);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.UndoButton]));
			w48.Position = 5;
			w48.Expand = false;
			w48.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.RedoButton = new global::Gtk.Button ();
			this.RedoButton.CanFocus = true;
			this.RedoButton.Name = "RedoButton";
			this.RedoButton.UseUnderline = true;
			this.RedoButton.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child RedoButton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w49 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w50 = new global::Gtk.HBox ();
			w50.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w51 = new global::Gtk.Image ();
			w51.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-redo", global::Gtk.IconSize.Menu);
			w50.Add (w51);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w53 = new global::Gtk.Label ();
			w50.Add (w53);
			w49.Add (w50);
			this.RedoButton.Add (w49);
			this.hbox7.Add (this.RedoButton);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.RedoButton]));
			w57.Position = 6;
			w57.Expand = false;
			w57.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator2 = new global::Gtk.VSeparator ();
			this.vseparator2.Name = "vseparator2";
			this.hbox7.Add (this.vseparator2);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator2]));
			w58.Position = 7;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ComboboxSelectNode = global::Gtk.ComboBox.NewText ();
			this.ComboboxSelectNode.Name = "ComboboxSelectNode";
			this.hbox7.Add (this.ComboboxSelectNode);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ComboboxSelectNode]));
			w59.Position = 8;
			w59.Expand = false;
			w59.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonCheckEmbedded = new global::Gtk.Button ();
			this.ButtonCheckEmbedded.CanFocus = true;
			this.ButtonCheckEmbedded.Name = "ButtonCheckEmbedded";
			this.ButtonCheckEmbedded.UseUnderline = true;
			this.ButtonCheckEmbedded.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonCheckEmbedded.Gtk.Container+ContainerChild
			global::Gtk.Alignment w60 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w61 = new global::Gtk.HBox ();
			w61.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			w61.Add (w62);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w64 = new global::Gtk.Label ();
			w61.Add (w64);
			w60.Add (w61);
			this.ButtonCheckEmbedded.Add (w60);
			this.hbox7.Add (this.ButtonCheckEmbedded);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonCheckEmbedded]));
			w68.Position = 9;
			w68.Expand = false;
			w68.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator5 = new global::Gtk.VSeparator ();
			this.vseparator5.Name = "vseparator5";
			this.hbox7.Add (this.vseparator5);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator5]));
			w69.Position = 10;
			w69.Expand = false;
			w69.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonReloadUSB = new global::Gtk.Button ();
			this.ButtonReloadUSB.CanFocus = true;
			this.ButtonReloadUSB.Name = "ButtonReloadUSB";
			this.ButtonReloadUSB.UseUnderline = true;
			this.ButtonReloadUSB.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonReloadUSB.Gtk.Container+ContainerChild
			global::Gtk.Alignment w70 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w71 = new global::Gtk.HBox ();
			w71.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w72 = new global::Gtk.Image ();
			w72.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			w71.Add (w72);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w74 = new global::Gtk.Label ();
			w71.Add (w74);
			w70.Add (w71);
			this.ButtonReloadUSB.Add (w70);
			this.hbox7.Add (this.ButtonReloadUSB);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonReloadUSB]));
			w78.Position = 11;
			w78.Expand = false;
			w78.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ComboboxSelectUsb = global::Gtk.ComboBox.NewText ();
			this.ComboboxSelectUsb.Name = "ComboboxSelectUsb";
			this.hbox7.Add (this.ComboboxSelectUsb);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ComboboxSelectUsb]));
			w79.Position = 12;
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonLoadEmbedded = new global::Gtk.Button ();
			this.ButtonLoadEmbedded.CanFocus = true;
			this.ButtonLoadEmbedded.Name = "ButtonLoadEmbedded";
			this.ButtonLoadEmbedded.UseUnderline = true;
			this.ButtonLoadEmbedded.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonLoadEmbedded.Gtk.Container+ContainerChild
			global::Gtk.Alignment w80 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w81 = new global::Gtk.HBox ();
			w81.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w82 = new global::Gtk.Image ();
			w82.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_bottom", global::Gtk.IconSize.Menu);
			w81.Add (w82);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w84 = new global::Gtk.Label ();
			w81.Add (w84);
			w80.Add (w81);
			this.ButtonLoadEmbedded.Add (w80);
			this.hbox7.Add (this.ButtonLoadEmbedded);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonLoadEmbedded]));
			w88.Position = 13;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hbox7.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator4]));
			w89.Position = 14;
			w89.Expand = false;
			w89.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonReadEthernet = new global::Gtk.Button ();
			this.ButtonReadEthernet.CanFocus = true;
			this.ButtonReadEthernet.Name = "ButtonReadEthernet";
			this.ButtonReadEthernet.UseUnderline = true;
			this.ButtonReadEthernet.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ButtonReadEthernet.Gtk.Container+ContainerChild
			global::Gtk.Alignment w90 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w91 = new global::Gtk.HBox ();
			w91.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w92 = new global::Gtk.Image ();
			w92.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			w91.Add (w92);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w94 = new global::Gtk.Label ();
			w91.Add (w94);
			w90.Add (w91);
			this.ButtonReadEthernet.Add (w90);
			this.hbox7.Add (this.ButtonReadEthernet);
			global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonReadEthernet]));
			w98.Position = 15;
			w98.Expand = false;
			w98.Fill = false;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w99.Position = 1;
			w99.Expand = false;
			w99.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w100 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w100.Position = 2;
			w100.Expand = false;
			w100.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 279;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.eventbox9 = new global::Gtk.EventBox ();
			this.eventbox9.HeightRequest = 24;
			this.eventbox9.Name = "eventbox9";
			// Container child eventbox9.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.LabelTreeView = new global::Gtk.Label ();
			this.LabelTreeView.Name = "LabelTreeView";
			this.LabelTreeView.Xpad = 8;
			this.LabelTreeView.Xalign = 0F;
			this.LabelTreeView.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.LabelTreeView.UseMarkup = true;
			this.hbox6.Add (this.LabelTreeView);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.LabelTreeView]));
			w101.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Up = new global::Gtk.Button ();
			this.Up.CanFocus = true;
			this.Up.Name = "Up";
			this.Up.UseUnderline = true;
			this.Up.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child Up.Gtk.Container+ContainerChild
			global::Gtk.Alignment w102 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w103 = new global::Gtk.HBox ();
			w103.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w104 = new global::Gtk.Image ();
			w104.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w103.Add (w104);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w106 = new global::Gtk.Label ();
			w103.Add (w106);
			w102.Add (w103);
			this.Up.Add (w102);
			this.hbox6.Add (this.Up);
			global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Up]));
			w110.Position = 1;
			w110.Expand = false;
			w110.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Down = new global::Gtk.Button ();
			this.Down.CanFocus = true;
			this.Down.Name = "Down";
			this.Down.UseUnderline = true;
			this.Down.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child Down.Gtk.Container+ContainerChild
			global::Gtk.Alignment w111 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w112 = new global::Gtk.HBox ();
			w112.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w113 = new global::Gtk.Image ();
			w113.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			w112.Add (w113);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w115 = new global::Gtk.Label ();
			w112.Add (w115);
			w111.Add (w112);
			this.Down.Add (w111);
			this.hbox6.Add (this.Down);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Down]));
			w119.Position = 2;
			w119.Expand = false;
			w119.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Reduce = new global::Gtk.Button ();
			this.Reduce.CanFocus = true;
			this.Reduce.Name = "Reduce";
			this.Reduce.UseUnderline = true;
			this.Reduce.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child Reduce.Gtk.Container+ContainerChild
			global::Gtk.Alignment w120 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w121 = new global::Gtk.HBox ();
			w121.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w122 = new global::Gtk.Image ();
			w122.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			w121.Add (w122);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w124 = new global::Gtk.Label ();
			w121.Add (w124);
			w120.Add (w121);
			this.Reduce.Add (w120);
			this.hbox6.Add (this.Reduce);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Reduce]));
			w128.Position = 3;
			w128.Expand = false;
			w128.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Expand = new global::Gtk.Button ();
			this.Expand.CanFocus = true;
			this.Expand.Name = "Expand";
			this.Expand.UseUnderline = true;
			this.Expand.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child Expand.Gtk.Container+ContainerChild
			global::Gtk.Alignment w129 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w130 = new global::Gtk.HBox ();
			w130.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w131 = new global::Gtk.Image ();
			w131.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			w130.Add (w131);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w133 = new global::Gtk.Label ();
			w130.Add (w133);
			w129.Add (w130);
			this.Expand.Add (w129);
			this.hbox6.Add (this.Expand);
			global::Gtk.Box.BoxChild w137 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Expand]));
			w137.Position = 4;
			w137.Expand = false;
			w137.Fill = false;
			this.eventbox9.Add (this.hbox6);
			this.vbox2.Add (this.eventbox9);
			global::Gtk.Box.BoxChild w139 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.eventbox9]));
			w139.Position = 0;
			w139.Expand = false;
			w139.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.ExplorerTreeView = new global::Gtk.TreeView ();
			this.ExplorerTreeView.CanFocus = true;
			this.ExplorerTreeView.Name = "ExplorerTreeView";
			this.scrolledwindow1.Add (this.ExplorerTreeView);
			this.hbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.scrolledwindow1]));
			w141.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.VBoxButtonNews = new global::Gtk.VBox ();
			this.VBoxButtonNews.Name = "VBoxButtonNews";
			this.VBoxButtonNews.Homogeneous = true;
			this.VBoxButtonNews.Spacing = 6;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.LabelButton = new global::Gtk.Label ();
			this.LabelButton.Name = "LabelButton";
			this.LabelButton.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.VBoxButtonNews.Add (this.LabelButton);
			global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.LabelButton]));
			w142.Position = 1;
			w142.Expand = false;
			w142.Fill = false;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.ButtonNew3 = new global::Gtk.Button ();
			this.ButtonNew3.CanFocus = true;
			this.ButtonNew3.Name = "ButtonNew3";
			this.ButtonNew3.UseUnderline = true;
			this.ButtonNew3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.VBoxButtonNews.Add (this.ButtonNew3);
			global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.ButtonNew3]));
			w143.Position = 2;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.ButtonNew2 = new global::Gtk.Button ();
			this.ButtonNew2.CanFocus = true;
			this.ButtonNew2.Name = "ButtonNew2";
			this.ButtonNew2.UseUnderline = true;
			this.ButtonNew2.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.VBoxButtonNews.Add (this.ButtonNew2);
			global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.ButtonNew2]));
			w144.Position = 3;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.ButtonNew1 = new global::Gtk.Button ();
			this.ButtonNew1.CanFocus = true;
			this.ButtonNew1.Name = "ButtonNew1";
			this.ButtonNew1.UseUnderline = true;
			this.ButtonNew1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.VBoxButtonNews.Add (this.ButtonNew1);
			global::Gtk.Box.BoxChild w145 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.ButtonNew1]));
			w145.Position = 4;
			this.hbox2.Add (this.VBoxButtonNews);
			global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.VBoxButtonNews]));
			w146.Position = 1;
			w146.Expand = false;
			w146.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w147 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w147.Position = 1;
			this.hpaned1.Add (this.vbox2);
			global::Gtk.Paned.PanedChild w148 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox2]));
			w148.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 643;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 596;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w149 = new global::Gtk.Viewport ();
			w149.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.MainNoteBook = new global::Gtk.Notebook ();
			this.MainNoteBook.CanFocus = true;
			this.MainNoteBook.Name = "MainNoteBook";
			this.MainNoteBook.CurrentPage = -1;
			this.MainNoteBook.ShowBorder = false;
			this.MainNoteBook.Scrollable = true;
			w149.Add (this.MainNoteBook);
			this.scrolledwindow2.Add (w149);
			this.hpaned2.Add (this.scrolledwindow2);
			global::Gtk.Paned.PanedChild w152 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.scrolledwindow2]));
			w152.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w153 = new global::Gtk.Viewport ();
			w153.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.SecondNoteBook = new global::Gtk.Notebook ();
			this.SecondNoteBook.CanFocus = true;
			this.SecondNoteBook.Name = "SecondNoteBook";
			this.SecondNoteBook.CurrentPage = -1;
			this.SecondNoteBook.ShowBorder = false;
			this.SecondNoteBook.Scrollable = true;
			w153.Add (this.SecondNoteBook);
			this.scrolledwindow3.Add (w153);
			this.hpaned2.Add (this.scrolledwindow3);
			this.vpaned1.Add (this.hpaned2);
			global::Gtk.Paned.PanedChild w157 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hpaned2]));
			w157.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.ViewNoteBook = new global::Gtk.Notebook ();
			this.ViewNoteBook.CanFocus = true;
			this.ViewNoteBook.Name = "ViewNoteBook";
			this.ViewNoteBook.CurrentPage = 1;
			this.ViewNoteBook.TabPos = ((global::Gtk.PositionType)(3));
			// Container child ViewNoteBook.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.HeightRequest = 26;
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.LabelInformation = new global::Gtk.Label ();
			this.LabelInformation.Name = "LabelInformation";
			this.LabelInformation.Xalign = 0F;
			this.LabelInformation.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.LabelInformation);
			global::Gtk.Box.BoxChild w158 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LabelInformation]));
			w158.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterInfo = new global::Gtk.ToggleButton ();
			this.ButtonFilterInfo.CanFocus = true;
			this.ButtonFilterInfo.Name = "ButtonFilterInfo";
			this.ButtonFilterInfo.UseUnderline = true;
			// Container child ButtonFilterInfo.Gtk.Container+ContainerChild
			global::Gtk.Alignment w159 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w160 = new global::Gtk.HBox ();
			w160.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w161 = new global::Gtk.Image ();
			w161.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			w160.Add (w161);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w163 = new global::Gtk.Label ();
			w160.Add (w163);
			w159.Add (w160);
			this.ButtonFilterInfo.Add (w159);
			this.hbox1.Add (this.ButtonFilterInfo);
			global::Gtk.Box.BoxChild w167 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterInfo]));
			w167.Position = 1;
			w167.Expand = false;
			w167.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterWarning = new global::Gtk.ToggleButton ();
			this.ButtonFilterWarning.CanFocus = true;
			this.ButtonFilterWarning.Name = "ButtonFilterWarning";
			this.ButtonFilterWarning.UseUnderline = true;
			// Container child ButtonFilterWarning.Gtk.Container+ContainerChild
			global::Gtk.Alignment w168 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w169 = new global::Gtk.HBox ();
			w169.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w170 = new global::Gtk.Image ();
			w170.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Menu);
			w169.Add (w170);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w172 = new global::Gtk.Label ();
			w169.Add (w172);
			w168.Add (w169);
			this.ButtonFilterWarning.Add (w168);
			this.hbox1.Add (this.ButtonFilterWarning);
			global::Gtk.Box.BoxChild w176 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterWarning]));
			w176.Position = 2;
			w176.Expand = false;
			w176.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterError = new global::Gtk.ToggleButton ();
			this.ButtonFilterError.CanFocus = true;
			this.ButtonFilterError.Name = "ButtonFilterError";
			this.ButtonFilterError.UseUnderline = true;
			// Container child ButtonFilterError.Gtk.Container+ContainerChild
			global::Gtk.Alignment w177 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w178 = new global::Gtk.HBox ();
			w178.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w179 = new global::Gtk.Image ();
			w179.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			w178.Add (w179);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w181 = new global::Gtk.Label ();
			w178.Add (w181);
			w177.Add (w178);
			this.ButtonFilterError.Add (w177);
			this.hbox1.Add (this.ButtonFilterError);
			global::Gtk.Box.BoxChild w185 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterError]));
			w185.Position = 3;
			w185.Expand = false;
			w185.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterQuestion = new global::Gtk.ToggleButton ();
			this.ButtonFilterQuestion.CanFocus = true;
			this.ButtonFilterQuestion.Name = "ButtonFilterQuestion";
			this.ButtonFilterQuestion.UseUnderline = true;
			// Container child ButtonFilterQuestion.Gtk.Container+ContainerChild
			global::Gtk.Alignment w186 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w187 = new global::Gtk.HBox ();
			w187.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w188 = new global::Gtk.Image ();
			w188.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-question", global::Gtk.IconSize.Menu);
			w187.Add (w188);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w190 = new global::Gtk.Label ();
			w187.Add (w190);
			w186.Add (w187);
			this.ButtonFilterQuestion.Add (w186);
			this.hbox1.Add (this.ButtonFilterQuestion);
			global::Gtk.Box.BoxChild w194 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterQuestion]));
			w194.Position = 4;
			w194.Expand = false;
			w194.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.EraseOutput = new global::Gtk.Button ();
			this.EraseOutput.CanFocus = true;
			this.EraseOutput.Name = "EraseOutput";
			this.EraseOutput.UseUnderline = true;
			// Container child EraseOutput.Gtk.Container+ContainerChild
			global::Gtk.Alignment w195 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w196 = new global::Gtk.HBox ();
			w196.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w197 = new global::Gtk.Image ();
			w197.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			w196.Add (w197);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w199 = new global::Gtk.Label ();
			w196.Add (w199);
			w195.Add (w196);
			this.EraseOutput.Add (w195);
			this.hbox1.Add (this.EraseOutput);
			global::Gtk.Box.BoxChild w203 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.EraseOutput]));
			w203.Position = 5;
			w203.Expand = false;
			w203.Fill = false;
			this.eventbox1.Add (this.hbox1);
			this.vbox4.Add (this.eventbox1);
			global::Gtk.Box.BoxChild w205 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.eventbox1]));
			w205.Position = 0;
			w205.Expand = false;
			w205.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.OutputTreeview = new global::Gtk.TreeView ();
			this.OutputTreeview.CanFocus = true;
			this.OutputTreeview.Name = "OutputTreeview";
			this.GtkScrolledWindow1.Add (this.OutputTreeview);
			this.vbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w207 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
			w207.Position = 1;
			this.ViewNoteBook.Add (this.vbox4);
			// Notebook tab
			this.OutputTab = new global::Gtk.Label ();
			this.OutputTab.Name = "OutputTab";
			this.OutputTab.LabelProp = global::Mono.Unix.Catalog.GetString ("OutputTab");
			this.ViewNoteBook.SetTabLabel (this.vbox4, this.OutputTab);
			this.OutputTab.ShowAll ();
			// Container child ViewNoteBook.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox ();
			this.eventbox2.HeightRequest = 26;
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LabelHistoric = new global::Gtk.Label ();
			this.LabelHistoric.Name = "LabelHistoric";
			this.LabelHistoric.Xalign = 0F;
			this.LabelHistoric.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox3.Add (this.LabelHistoric);
			global::Gtk.Box.BoxChild w209 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LabelHistoric]));
			w209.Position = 0;
			this.eventbox2.Add (this.hbox3);
			this.vbox5.Add (this.eventbox2);
			global::Gtk.Box.BoxChild w211 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.eventbox2]));
			w211.Position = 0;
			w211.Expand = false;
			w211.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.HistoricTreeView = new global::Gtk.TreeView ();
			this.HistoricTreeView.CanFocus = true;
			this.HistoricTreeView.Name = "HistoricTreeView";
			this.GtkScrolledWindow2.Add (this.HistoricTreeView);
			this.vbox5.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w213 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow2]));
			w213.Position = 1;
			this.ViewNoteBook.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w214 = ((global::Gtk.Notebook.NotebookChild)(this.ViewNoteBook [this.vbox5]));
			w214.Position = 1;
			// Notebook tab
			this.HistoryTab = new global::Gtk.Label ();
			this.HistoryTab.Name = "HistoryTab";
			this.HistoryTab.LabelProp = global::Mono.Unix.Catalog.GetString ("HistoryTab");
			this.ViewNoteBook.SetTabLabel (this.vbox5, this.HistoryTab);
			this.HistoryTab.ShowAll ();
			this.vpaned1.Add (this.ViewNoteBook);
			this.hpaned1.Add (this.vpaned1);
			global::Gtk.Paned.PanedChild w216 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned1]));
			w216.Resize = false;
			w216.Shrink = false;
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w217 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w217.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.HeightRequest = 25;
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.LabelInfoProject = new global::Gtk.Label ();
			this.LabelInfoProject.Name = "LabelInfoProject";
			this.LabelInfoProject.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox4.Add (this.LabelInfoProject);
			global::Gtk.Box.BoxChild w218 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.LabelInfoProject]));
			w218.Position = 0;
			w218.Expand = false;
			w218.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox4.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w219 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator3]));
			w219.Position = 1;
			w219.Expand = false;
			w219.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.LabelPathProject = new global::Gtk.Label ();
			this.LabelPathProject.Name = "LabelPathProject";
			this.LabelPathProject.Xalign = 0F;
			this.LabelPathProject.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox4.Add (this.LabelPathProject);
			global::Gtk.Box.BoxChild w220 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.LabelPathProject]));
			w220.Position = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ProgressBar = new global::Gtk.ProgressBar ();
			this.ProgressBar.Name = "ProgressBar";
			this.ProgressBar.Text = "";
			this.ProgressBar.PulseStep = 0;
			this.hbox4.Add (this.ProgressBar);
			global::Gtk.Box.BoxChild w221 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ProgressBar]));
			w221.Position = 3;
			w221.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ExpendHistoryPanel = new global::Gtk.Button ();
			this.ExpendHistoryPanel.CanFocus = true;
			this.ExpendHistoryPanel.Name = "ExpendHistoryPanel";
			this.ExpendHistoryPanel.UseUnderline = true;
			this.ExpendHistoryPanel.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ExpendHistoryPanel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w222 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w223 = new global::Gtk.HBox ();
			w223.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w224 = new global::Gtk.Image ();
			w224.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			w223.Add (w224);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w226 = new global::Gtk.Label ();
			w223.Add (w226);
			w222.Add (w223);
			this.ExpendHistoryPanel.Add (w222);
			this.hbox4.Add (this.ExpendHistoryPanel);
			global::Gtk.Box.BoxChild w230 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ExpendHistoryPanel]));
			w230.Position = 4;
			w230.Expand = false;
			w230.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ReduceHistoryPanel = new global::Gtk.Button ();
			this.ReduceHistoryPanel.CanFocus = true;
			this.ReduceHistoryPanel.Name = "ReduceHistoryPanel";
			this.ReduceHistoryPanel.UseUnderline = true;
			this.ReduceHistoryPanel.Relief = ((global::Gtk.ReliefStyle)(2));
			// Container child ReduceHistoryPanel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w231 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w232 = new global::Gtk.HBox ();
			w232.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w233 = new global::Gtk.Image ();
			w233.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			w232.Add (w233);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w235 = new global::Gtk.Label ();
			w232.Add (w235);
			w231.Add (w232);
			this.ReduceHistoryPanel.Add (w231);
			this.hbox4.Add (this.ReduceHistoryPanel);
			global::Gtk.Box.BoxChild w239 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ReduceHistoryPanel]));
			w239.Position = 5;
			w239.Expand = false;
			w239.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w240 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w240.Position = 4;
			w240.Expand = false;
			w240.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1530;
			this.DefaultHeight = 1224;
			this.ButtonReadEthernet.Hide ();
			this.Expand.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.newAction.Activated += new global::System.EventHandler (this.OnFileActionActivated);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.CreateConfigurationAction.Activated += new global::System.EventHandler (this.OnCreateConfigurationActionActivated);
			this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForwardActionActivated);
			this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackActionActivated);
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
			this.undoAction.Activated += new global::System.EventHandler (this.OnUndoActionActivated);
			this.redoAction.Activated += new global::System.EventHandler (this.OnRedoActionActivated);
			this.MyPreferenceAction.Activated += new global::System.EventHandler (this.OnMyPreferenceActionActivated);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
			this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
			this.ExtractEmbeddedAction.Activated += new global::System.EventHandler (this.OnVerifyEmbeddedActionActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.ButtonNewProject.Clicked += new global::System.EventHandler (this.OnButtonNewProjectClicked);
			this.ButtonOpenProject.Clicked += new global::System.EventHandler (this.OnButtonOpenProjectClicked);
			this.ButtonSaveProject.Clicked += new global::System.EventHandler (this.OnButtonSaveProjectClicked);
			this.ButtonSaveAllProject.Clicked += new global::System.EventHandler (this.OnButtonSaveAllProjectClicked);
			this.UndoButton.Clicked += new global::System.EventHandler (this.OnUndoButtonClicked);
			this.RedoButton.Clicked += new global::System.EventHandler (this.OnRedoButtonClicked);
			this.ComboboxSelectNode.Changed += new global::System.EventHandler (this.OnComboboxSelectNodeChanged);
			this.ButtonCheckEmbedded.Clicked += new global::System.EventHandler (this.OnButtonCheckEmbeddedClicked);
			this.ButtonReloadUSB.Clicked += new global::System.EventHandler (this.OnButtonReloadUSBClicked);
			this.ComboboxSelectUsb.Changed += new global::System.EventHandler (this.OnComboboxSelectNodeChanged);
			this.ButtonLoadEmbedded.Clicked += new global::System.EventHandler (this.OnButtonLoadEmbeddedClicked);
			this.ButtonReadEthernet.Clicked += new global::System.EventHandler (this.OnButtonReadEthernetClicked);
			this.Up.Clicked += new global::System.EventHandler (this.OnUpClicked);
			this.Down.Clicked += new global::System.EventHandler (this.OnDownClicked);
			this.Reduce.Clicked += new global::System.EventHandler (this.OnReduceClicked);
			this.Expand.Clicked += new global::System.EventHandler (this.OnIncreaseClicked);
			this.ExplorerTreeView.CursorChanged += new global::System.EventHandler (this.OnExplorerTreeViewCursorChanged);
			this.ButtonNew1.Clicked += new global::System.EventHandler (this.OnButtonNew1Clicked);
			this.MainNoteBook.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnMainNoteBookSwitchPage);
			this.ButtonFilterInfo.Toggled += new global::System.EventHandler (this.OnButtonFilterInfoToggled);
			this.ButtonFilterWarning.Toggled += new global::System.EventHandler (this.OnButtonFilterWarningToggled);
			this.ButtonFilterError.Toggled += new global::System.EventHandler (this.OnButtonFilterErrorToggled);
			this.ButtonFilterQuestion.Toggled += new global::System.EventHandler (this.OnButtonFilterQuestionToggled);
			this.EraseOutput.Clicked += new global::System.EventHandler (this.OnEraseOutputClicked);
			this.HistoricTreeView.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnHistoricTreeViewButtonReleaseEvent);
			this.ExpendHistoryPanel.Clicked += new global::System.EventHandler (this.OnExpendHistoryPanelClicked);
			this.ReduceHistoryPanel.Clicked += new global::System.EventHandler (this.OnReduceHistoryPanelClicked);
		}
	}
}
