
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class InstanceProperties
	{
		private global::Gtk.VPaned vpaned1;
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label LabelChildTreeView;
		private global::Gtk.ComboBox ComboboxNumberOfInstance;
		private global::Gtk.Button AddNewInstance;
		private global::Gtk.VSeparator vseparator3;
		private global::Gtk.Button DeleteInstance;
		private global::Gtk.ScrolledWindow scrolledwindow3;
		private global::Gtk.TreeView ChildTreeView;
		private global::Gtk.VBox vbox6;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label NoteLabel;
		private global::Gtk.ScrolledWindow scrolledwindow5;
		private global::Gtk.TextView TextViewNote;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.InstanceProperties
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xPLduinoManager.InstanceProperties";
			// Container child xPLduinoManager.InstanceProperties.Gtk.Container+ContainerChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 327;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.LabelChildTreeView = new global::Gtk.Label ();
			this.LabelChildTreeView.Name = "LabelChildTreeView";
			this.LabelChildTreeView.Xalign = 0F;
			this.LabelChildTreeView.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox2.Add (this.LabelChildTreeView);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LabelChildTreeView]));
			w1.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ComboboxNumberOfInstance = global::Gtk.ComboBox.NewText ();
			this.ComboboxNumberOfInstance.Name = "ComboboxNumberOfInstance";
			this.hbox2.Add (this.ComboboxNumberOfInstance);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ComboboxNumberOfInstance]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.AddNewInstance = new global::Gtk.Button ();
			this.AddNewInstance.CanFocus = true;
			this.AddNewInstance.Name = "AddNewInstance";
			this.AddNewInstance.UseUnderline = true;
			this.AddNewInstance.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox2.Add (this.AddNewInstance);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.AddNewInstance]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox2.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vseparator3]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.DeleteInstance = new global::Gtk.Button ();
			this.DeleteInstance.CanFocus = true;
			this.DeleteInstance.Name = "DeleteInstance";
			this.DeleteInstance.UseUnderline = true;
			this.DeleteInstance.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox2.Add (this.DeleteInstance);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.DeleteInstance]));
			w5.Position = 4;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.ChildTreeView = new global::Gtk.TreeView ();
			this.ChildTreeView.CanFocus = true;
			this.ChildTreeView.Name = "ChildTreeView";
			this.scrolledwindow3.Add (this.ChildTreeView);
			this.vbox1.Add (this.scrolledwindow3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.scrolledwindow3]));
			w8.Position = 1;
			this.vpaned1.Add (this.vbox1);
			global::Gtk.Paned.PanedChild w9 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.vbox1]));
			w9.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.NoteLabel = new global::Gtk.Label ();
			this.NoteLabel.Name = "NoteLabel";
			this.NoteLabel.Xalign = 0F;
			this.NoteLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("label5");
			this.hbox1.Add (this.NoteLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.NoteLabel]));
			w10.Position = 0;
			this.vbox6.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox1]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.scrolledwindow5 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow5.CanFocus = true;
			this.scrolledwindow5.Name = "scrolledwindow5";
			this.scrolledwindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow5.Gtk.Container+ContainerChild
			this.TextViewNote = new global::Gtk.TextView ();
			this.TextViewNote.CanFocus = true;
			this.TextViewNote.Name = "TextViewNote";
			this.scrolledwindow5.Add (this.TextViewNote);
			this.vbox6.Add (this.scrolledwindow5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.scrolledwindow5]));
			w13.Position = 1;
			this.vpaned1.Add (this.vbox6);
			this.Add (this.vpaned1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.hbox1.Hide ();
			this.Hide ();
			this.AddNewInstance.Clicked += new global::System.EventHandler (this.OnAddNewInstanceClicked);
			this.DeleteInstance.Clicked += new global::System.EventHandler (this.OnDeleteInstanceClicked);
			this.ChildTreeView.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnChildTreeViewButtonReleaseEvent);
			this.ChildTreeView.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnChildTreeViewKeyReleaseEvent);
			this.TextViewNote.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnTextViewNoteFocusOutEvent);
			this.TextViewNote.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnTextViewNoteKeyReleaseEvent);
		}
	}
}
