
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class CustomerEdit
	{
		private global::Gtk.HPaned hpaned2;
		
		private global::Gtk.ScrolledWindow ScrolledWindowTextEdit1;
		
		private global::Gtk.ScrolledWindow ScrolledWindowTextEdit2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.CustomerEdit
			global::Stetic.BinContainer.Attach (this);
			this.Name = "xPLduinoManager.CustomerEdit";
			// Container child xPLduinoManager.CustomerEdit.Gtk.Container+ContainerChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 469;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.ScrolledWindowTextEdit1 = new global::Gtk.ScrolledWindow ();
			this.ScrolledWindowTextEdit1.CanFocus = true;
			this.ScrolledWindowTextEdit1.Name = "ScrolledWindowTextEdit1";
			this.ScrolledWindowTextEdit1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.hpaned2.Add (this.ScrolledWindowTextEdit1);
			global::Gtk.Paned.PanedChild w1 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.ScrolledWindowTextEdit1]));
			w1.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.ScrolledWindowTextEdit2 = new global::Gtk.ScrolledWindow ();
			this.ScrolledWindowTextEdit2.CanFocus = true;
			this.ScrolledWindowTextEdit2.Name = "ScrolledWindowTextEdit2";
			this.ScrolledWindowTextEdit2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.hpaned2.Add (this.ScrolledWindowTextEdit2);
			this.Add (this.hpaned2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
