
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class NewProject
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label LabelProjectName;
		private global::Gtk.Entry EntryNameProject;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label LabelAuhorName;
		private global::Gtk.Entry EntryAuthorProject;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label LabelPath;
		private global::Gtk.FileChooserButton ButtonChooseFolder;
		private global::Gtk.Label LabelError;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.NewProject
			this.Name = "xPLduinoManager.NewProject";
			this.Title = global::Mono.Unix.Catalog.GetString ("Nouveau Projet");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			// Internal child xPLduinoManager.NewProject.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.LabelProjectName = new global::Gtk.Label ();
			this.LabelProjectName.WidthRequest = 120;
			this.LabelProjectName.Name = "LabelProjectName";
			this.LabelProjectName.Xalign = 0F;
			this.LabelProjectName.LabelProp = global::Mono.Unix.Catalog.GetString ("Nom du projet :");
			this.hbox1.Add (this.LabelProjectName);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LabelProjectName]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.EntryNameProject = new global::Gtk.Entry ();
			this.EntryNameProject.CanFocus = true;
			this.EntryNameProject.Name = "EntryNameProject";
			this.EntryNameProject.Text = global::Mono.Unix.Catalog.GetString ("NomDuProjet");
			this.EntryNameProject.IsEditable = true;
			this.EntryNameProject.MaxLength = 16;
			this.EntryNameProject.InvisibleChar = '●';
			this.hbox1.Add (this.EntryNameProject);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.EntryNameProject]));
			w3.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.LabelAuhorName = new global::Gtk.Label ();
			this.LabelAuhorName.WidthRequest = 120;
			this.LabelAuhorName.Name = "LabelAuhorName";
			this.LabelAuhorName.Xalign = 0F;
			this.LabelAuhorName.LabelProp = global::Mono.Unix.Catalog.GetString ("Auteur du projet :");
			this.hbox2.Add (this.LabelAuhorName);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LabelAuhorName]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.EntryAuthorProject = new global::Gtk.Entry ();
			this.EntryAuthorProject.CanFocus = true;
			this.EntryAuthorProject.Name = "EntryAuthorProject";
			this.EntryAuthorProject.Text = global::Mono.Unix.Catalog.GetString ("AuteurDuProjet");
			this.EntryAuthorProject.IsEditable = true;
			this.EntryAuthorProject.InvisibleChar = '●';
			this.hbox2.Add (this.EntryAuthorProject);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.EntryAuthorProject]));
			w6.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LabelPath = new global::Gtk.Label ();
			this.LabelPath.WidthRequest = 120;
			this.LabelPath.Name = "LabelPath";
			this.LabelPath.Xalign = 0F;
			this.LabelPath.LabelProp = global::Mono.Unix.Catalog.GetString ("Chemin du projet :");
			this.hbox3.Add (this.LabelPath);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LabelPath]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.ButtonChooseFolder = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Selectionner un dossier"), ((global::Gtk.FileChooserAction)(2)));
			this.ButtonChooseFolder.Name = "ButtonChooseFolder";
			this.hbox3.Add (this.ButtonChooseFolder);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.ButtonChooseFolder]));
			w9.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.LabelError = new global::Gtk.Label ();
			this.LabelError.Name = "LabelError";
			this.LabelError.Xalign = 0F;
			this.vbox2.Add (this.LabelError);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.LabelError]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Internal child xPLduinoManager.NewProject.ActionArea
			global::Gtk.HButtonBox w13 = this.ActionArea;
			w13.Name = "dialog1_ActionArea";
			w13.Spacing = 10;
			w13.BorderWidth = ((uint)(5));
			w13.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonCancel]));
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w15 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w13 [this.buttonOk]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 513;
			this.DefaultHeight = 156;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.EntryNameProject.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler (this.OnEntryNameProjectKeyReleaseEvent);
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
