
// This file has been generated by the GUI designer. Do not modify.
namespace xPLduinoManager
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action newAction;
		
		private global::Gtk.Action openAction;
		
		private global::Gtk.Action CreateConfigurationAction;
		
		private global::Gtk.Action ToolsAction;
		
		private global::Gtk.Action FentreAction;
		
		private global::Gtk.Action goForwardAction;
		
		private global::Gtk.Action goBackAction;
		
		private global::Gtk.Action closeAction;
		
		private global::Gtk.Action quitAction;
		
		private global::Gtk.Action EditAction;
		
		private global::Gtk.Action undoAction;
		
		private global::Gtk.Action redoAction;
		
		private global::Gtk.Action MyPreferenceAction;
		
		private global::Gtk.Action saveAction;
		
		private global::Gtk.Action saveAsAction;
		
		private global::Gtk.Action HelpAction;
		
		private global::Gtk.Action aboutAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Button ButtonNewProject;
		
		private global::Gtk.Button ButtonOpenProject;
		
		private global::Gtk.Button ButtonSaveProject;
		
		private global::Gtk.Button ButtonSaveAllProject;
		
		private global::Gtk.VSeparator vseparator1;
		
		private global::Gtk.Button UndoButton;
		
		private global::Gtk.Button RedoButton;
		
		private global::Gtk.VSeparator vseparator5;
		
		private global::Gtk.Button ButtonReloadUSB;
		
		private global::Gtk.ComboBox ComboboxSelectUsb;
		
		private global::Gtk.VSeparator vseparator4;
		
		private global::Gtk.Button ButtonReadEthernet;
		
		private global::Gtk.HSeparator hseparator1;
		
		private global::Gtk.HPaned hpaned1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.EventBox eventbox9;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label LabelTreeView;
		
		private global::Gtk.Button Up;
		
		private global::Gtk.Button Down;
		
		private global::Gtk.Button Reduce;
		
		private global::Gtk.Button Expand;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TreeView ExplorerTreeView;
		
		private global::Gtk.VBox VBoxButtonNews;
		
		private global::Gtk.Label LabelButton;
		
		private global::Gtk.Button ButtonNew3;
		
		private global::Gtk.Button ButtonNew2;
		
		private global::Gtk.Button ButtonNew1;
		
		private global::Gtk.VPaned vpaned1;
		
		private global::Gtk.HPaned hpaned2;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::Gtk.Notebook MainNoteBook;
		
		private global::Gtk.ScrolledWindow scrolledwindow3;
		
		private global::Gtk.Notebook SecondNoteBook;
		
		private global::Gtk.Notebook ViewNoteBook;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.EventBox eventbox1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label LabelInformation;
		
		private global::Gtk.ToggleButton ButtonFilterInfo;
		
		private global::Gtk.ToggleButton ButtonFilterWarning;
		
		private global::Gtk.ToggleButton ButtonFilterError;
		
		private global::Gtk.ToggleButton ButtonFilterQuestion;
		
		private global::Gtk.Button EraseOutput;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView OutputTreeview;
		
		private global::Gtk.Label OutputTab;
		
		private global::Gtk.VBox vbox5;
		
		private global::Gtk.EventBox eventbox2;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label LabelHistoric;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		
		private global::Gtk.TreeView HistoricTreeView;
		
		private global::Gtk.Label HistoryTab;
		
		private global::Gtk.VBox vbox6;
		
		private global::Gtk.EventBox eventbox3;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label LabelCompilLog;
		
		private global::Gtk.Button ExportLogButton;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TextView TextViewCompilLog;
		
		private global::Gtk.Label CompilLog;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label LabelInfoProject;
		
		private global::Gtk.VSeparator vseparator3;
		
		private global::Gtk.Label LabelPathProject;
		
		private global::Gtk.ProgressBar ProgressBar;
		
		private global::Gtk.Button ExpendHistoryPanel;
		
		private global::Gtk.Button ReduceHistoryPanel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget xPLduinoManager.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.newAction = new global::Gtk.Action ("newAction", global::Mono.Unix.Catalog.GetString ("New Project"), null, "gtk-new");
			this.newAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("New Project");
			w1.Add (this.newAction, null);
			this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open Project"), null, "gtk-open");
			this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Project");
			w1.Add (this.openAction, null);
			this.CreateConfigurationAction = new global::Gtk.Action ("CreateConfigurationAction", global::Mono.Unix.Catalog.GetString ("Create Configuration"), null, null);
			this.CreateConfigurationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create Configuration");
			w1.Add (this.CreateConfigurationAction, "<Primary><Mod2>w");
			this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
			this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
			w1.Add (this.ToolsAction, null);
			this.FentreAction = new global::Gtk.Action ("FentreAction", global::Mono.Unix.Catalog.GetString ("Fenêtre"), null, null);
			this.FentreAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fenêtre");
			w1.Add (this.FentreAction, null);
			this.goForwardAction = new global::Gtk.Action ("goForwardAction", global::Mono.Unix.Catalog.GetString ("Fenêtre suivante"), null, "gtk-go-forward");
			this.goForwardAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fenêtre suivante");
			w1.Add (this.goForwardAction, "<Primary><Mod2>Page_Up");
			this.goBackAction = new global::Gtk.Action ("goBackAction", global::Mono.Unix.Catalog.GetString ("Fenêtre précédente"), null, "gtk-go-back");
			this.goBackAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Fenêtre précédente");
			w1.Add (this.goBackAction, "<Primary><Mod2>Page_Down");
			this.closeAction = new global::Gtk.Action ("closeAction", global::Mono.Unix.Catalog.GetString ("Tout fermer"), null, "gtk-close");
			this.closeAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tout fermer");
			w1.Add (this.closeAction, "<Primary><Alt><Mod2>w");
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.quitAction, null);
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("Undo"), null, "gtk-undo");
			this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Undo");
			w1.Add (this.undoAction, "<Primary><Mod2>z");
			this.redoAction = new global::Gtk.Action ("redoAction", global::Mono.Unix.Catalog.GetString ("Redo"), null, "gtk-redo");
			this.redoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Redo");
			w1.Add (this.redoAction, "<Primary><Mod2>y");
			this.MyPreferenceAction = new global::Gtk.Action ("MyPreferenceAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, "gtk-preferences");
			this.MyPreferenceAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.MyPreferenceAction, "<Primary><Alt><Mod2>p");
			this.saveAction = new global::Gtk.Action ("saveAction", global::Mono.Unix.Catalog.GetString ("Save"), null, "gtk-save");
			this.saveAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save");
			w1.Add (this.saveAction, null);
			this.saveAsAction = new global::Gtk.Action ("saveAsAction", global::Mono.Unix.Catalog.GetString ("Save All"), null, "gtk-save-as");
			this.saveAsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Save All");
			w1.Add (this.saveAsAction, "<Primary><Mod2>d");
			this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
			this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.HelpAction, null);
			this.aboutAction = new global::Gtk.Action ("aboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-about");
			this.aboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
			w1.Add (this.aboutAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "xPLduinoManager.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("xPLduino - Manager");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("xPLduinoManager.Pictures.Project.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child xPLduinoManager.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='newAction' action='newAction'/><menuitem name='openAction' action='openAction'/><separator/><menuitem name='saveAction' action='saveAction'/><menuitem name='saveAsAction' action='saveAsAction'/><separator/><menuitem name='quitAction' action='quitAction'/></menu><menu name='EditAction' action='EditAction'><menuitem name='undoAction' action='undoAction'/><menuitem name='redoAction' action='redoAction'/><separator/><menuitem name='MyPreferenceAction' action='MyPreferenceAction'/></menu><menu name='FentreAction' action='FentreAction'><menuitem name='goForwardAction' action='goForwardAction'/><menuitem name='goBackAction' action='goBackAction'/><separator/><menuitem name='closeAction' action='closeAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='aboutAction' action='aboutAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonNewProject = new global::Gtk.Button ();
			this.ButtonNewProject.Name = "ButtonNewProject";
			this.ButtonNewProject.UseUnderline = true;
			this.ButtonNewProject.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-new", global::Gtk.IconSize.Menu);
			this.ButtonNewProject.Image = w3;
			this.hbox7.Add (this.ButtonNewProject);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonNewProject]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonOpenProject = new global::Gtk.Button ();
			this.ButtonOpenProject.Name = "ButtonOpenProject";
			this.ButtonOpenProject.UseUnderline = true;
			this.ButtonOpenProject.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.ButtonOpenProject.Image = w5;
			this.hbox7.Add (this.ButtonOpenProject);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonOpenProject]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonSaveProject = new global::Gtk.Button ();
			this.ButtonSaveProject.Name = "ButtonSaveProject";
			this.ButtonSaveProject.UseUnderline = true;
			this.ButtonSaveProject.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save", global::Gtk.IconSize.Menu);
			this.ButtonSaveProject.Image = w7;
			this.hbox7.Add (this.ButtonSaveProject);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonSaveProject]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonSaveAllProject = new global::Gtk.Button ();
			this.ButtonSaveAllProject.Name = "ButtonSaveAllProject";
			this.ButtonSaveAllProject.UseUnderline = true;
			this.ButtonSaveAllProject.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			this.ButtonSaveAllProject.Image = w9;
			this.hbox7.Add (this.ButtonSaveAllProject);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonSaveAllProject]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator ();
			this.vseparator1.Name = "vseparator1";
			this.hbox7.Add (this.vseparator1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator1]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.UndoButton = new global::Gtk.Button ();
			this.UndoButton.CanFocus = true;
			this.UndoButton.Name = "UndoButton";
			this.UndoButton.UseUnderline = true;
			this.UndoButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-undo", global::Gtk.IconSize.Menu);
			this.UndoButton.Image = w12;
			this.hbox7.Add (this.UndoButton);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.UndoButton]));
			w13.Position = 5;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.RedoButton = new global::Gtk.Button ();
			this.RedoButton.CanFocus = true;
			this.RedoButton.Name = "RedoButton";
			this.RedoButton.UseUnderline = true;
			this.RedoButton.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-redo", global::Gtk.IconSize.Menu);
			this.RedoButton.Image = w14;
			this.hbox7.Add (this.RedoButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.RedoButton]));
			w15.Position = 6;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator5 = new global::Gtk.VSeparator ();
			this.vseparator5.Name = "vseparator5";
			this.hbox7.Add (this.vseparator5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator5]));
			w16.Position = 7;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonReloadUSB = new global::Gtk.Button ();
			this.ButtonReloadUSB.CanFocus = true;
			this.ButtonReloadUSB.Name = "ButtonReloadUSB";
			this.ButtonReloadUSB.UseUnderline = true;
			this.ButtonReloadUSB.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-refresh", global::Gtk.IconSize.Menu);
			this.ButtonReloadUSB.Image = w17;
			this.hbox7.Add (this.ButtonReloadUSB);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonReloadUSB]));
			w18.Position = 8;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ComboboxSelectUsb = global::Gtk.ComboBox.NewText ();
			this.ComboboxSelectUsb.Name = "ComboboxSelectUsb";
			this.hbox7.Add (this.ComboboxSelectUsb);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ComboboxSelectUsb]));
			w19.Position = 9;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vseparator4 = new global::Gtk.VSeparator ();
			this.vseparator4.Name = "vseparator4";
			this.hbox7.Add (this.vseparator4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vseparator4]));
			w20.Position = 10;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.ButtonReadEthernet = new global::Gtk.Button ();
			this.ButtonReadEthernet.CanFocus = true;
			this.ButtonReadEthernet.Name = "ButtonReadEthernet";
			this.ButtonReadEthernet.UseUnderline = true;
			this.ButtonReadEthernet.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-media-play", global::Gtk.IconSize.Menu);
			this.ButtonReadEthernet.Image = w21;
			this.hbox7.Add (this.ButtonReadEthernet);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.ButtonReadEthernet]));
			w22.Position = 11;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox1.Add (this.hbox7);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox7]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox1.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 279;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			// Container child vbox2.Gtk.Box+BoxChild
			this.eventbox9 = new global::Gtk.EventBox ();
			this.eventbox9.HeightRequest = 24;
			this.eventbox9.Name = "eventbox9";
			// Container child eventbox9.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.LabelTreeView = new global::Gtk.Label ();
			this.LabelTreeView.Name = "LabelTreeView";
			this.LabelTreeView.Xpad = 8;
			this.LabelTreeView.Xalign = 0F;
			this.LabelTreeView.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.LabelTreeView.UseMarkup = true;
			this.hbox6.Add (this.LabelTreeView);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.LabelTreeView]));
			w25.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Up = new global::Gtk.Button ();
			this.Up.CanFocus = true;
			this.Up.Name = "Up";
			this.Up.UseUnderline = true;
			this.Up.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			this.Up.Image = w26;
			this.hbox6.Add (this.Up);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Up]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Down = new global::Gtk.Button ();
			this.Down.CanFocus = true;
			this.Down.Name = "Down";
			this.Down.UseUnderline = true;
			this.Down.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			this.Down.Image = w28;
			this.hbox6.Add (this.Down);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Down]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Reduce = new global::Gtk.Button ();
			this.Reduce.CanFocus = true;
			this.Reduce.Name = "Reduce";
			this.Reduce.UseUnderline = true;
			this.Reduce.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-back", global::Gtk.IconSize.Menu);
			this.Reduce.Image = w30;
			this.hbox6.Add (this.Reduce);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Reduce]));
			w31.Position = 3;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.Expand = new global::Gtk.Button ();
			this.Expand.CanFocus = true;
			this.Expand.Name = "Expand";
			this.Expand.UseUnderline = true;
			this.Expand.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-forward", global::Gtk.IconSize.Menu);
			this.Expand.Image = w32;
			this.hbox6.Add (this.Expand);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.Expand]));
			w33.Position = 4;
			w33.Expand = false;
			w33.Fill = false;
			this.eventbox9.Add (this.hbox6);
			this.vbox2.Add (this.eventbox9);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.eventbox9]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.ExplorerTreeView = new global::Gtk.TreeView ();
			this.ExplorerTreeView.CanFocus = true;
			this.ExplorerTreeView.Name = "ExplorerTreeView";
			this.scrolledwindow1.Add (this.ExplorerTreeView);
			this.hbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.scrolledwindow1]));
			w37.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.VBoxButtonNews = new global::Gtk.VBox ();
			this.VBoxButtonNews.Name = "VBoxButtonNews";
			this.VBoxButtonNews.Homogeneous = true;
			this.VBoxButtonNews.Spacing = 6;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.LabelButton = new global::Gtk.Label ();
			this.LabelButton.Name = "LabelButton";
			this.LabelButton.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.VBoxButtonNews.Add (this.LabelButton);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.LabelButton]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.ButtonNew3 = new global::Gtk.Button ();
			this.ButtonNew3.CanFocus = true;
			this.ButtonNew3.Name = "ButtonNew3";
			this.ButtonNew3.UseUnderline = true;
			this.ButtonNew3.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.VBoxButtonNews.Add (this.ButtonNew3);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.ButtonNew3]));
			w39.Position = 2;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.ButtonNew2 = new global::Gtk.Button ();
			this.ButtonNew2.CanFocus = true;
			this.ButtonNew2.Name = "ButtonNew2";
			this.ButtonNew2.UseUnderline = true;
			this.ButtonNew2.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.VBoxButtonNews.Add (this.ButtonNew2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.ButtonNew2]));
			w40.Position = 3;
			// Container child VBoxButtonNews.Gtk.Box+BoxChild
			this.ButtonNew1 = new global::Gtk.Button ();
			this.ButtonNew1.CanFocus = true;
			this.ButtonNew1.Name = "ButtonNew1";
			this.ButtonNew1.UseUnderline = true;
			this.ButtonNew1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.VBoxButtonNews.Add (this.ButtonNew1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.VBoxButtonNews [this.ButtonNew1]));
			w41.Position = 4;
			this.hbox2.Add (this.VBoxButtonNews);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.VBoxButtonNews]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w43.Position = 1;
			this.hpaned1.Add (this.vbox2);
			global::Gtk.Paned.PanedChild w44 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox2]));
			w44.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vpaned1 = new global::Gtk.VPaned ();
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 643;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.hpaned2 = new global::Gtk.HPaned ();
			this.hpaned2.CanFocus = true;
			this.hpaned2.Name = "hpaned2";
			this.hpaned2.Position = 596;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w45 = new global::Gtk.Viewport ();
			w45.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.MainNoteBook = new global::Gtk.Notebook ();
			this.MainNoteBook.CanFocus = true;
			this.MainNoteBook.Name = "MainNoteBook";
			this.MainNoteBook.CurrentPage = -1;
			this.MainNoteBook.ShowBorder = false;
			this.MainNoteBook.Scrollable = true;
			w45.Add (this.MainNoteBook);
			this.scrolledwindow2.Add (w45);
			this.hpaned2.Add (this.scrolledwindow2);
			global::Gtk.Paned.PanedChild w48 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.scrolledwindow2]));
			w48.Resize = false;
			// Container child hpaned2.Gtk.Paned+PanedChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			global::Gtk.Viewport w49 = new global::Gtk.Viewport ();
			w49.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport1.Gtk.Container+ContainerChild
			this.SecondNoteBook = new global::Gtk.Notebook ();
			this.SecondNoteBook.CanFocus = true;
			this.SecondNoteBook.Name = "SecondNoteBook";
			this.SecondNoteBook.CurrentPage = -1;
			this.SecondNoteBook.ShowBorder = false;
			this.SecondNoteBook.Scrollable = true;
			w49.Add (this.SecondNoteBook);
			this.scrolledwindow3.Add (w49);
			this.hpaned2.Add (this.scrolledwindow3);
			this.vpaned1.Add (this.hpaned2);
			global::Gtk.Paned.PanedChild w53 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hpaned2]));
			w53.Resize = false;
			// Container child vpaned1.Gtk.Paned+PanedChild
			this.ViewNoteBook = new global::Gtk.Notebook ();
			this.ViewNoteBook.CanFocus = true;
			this.ViewNoteBook.Name = "ViewNoteBook";
			this.ViewNoteBook.CurrentPage = 2;
			this.ViewNoteBook.TabPos = ((global::Gtk.PositionType)(3));
			// Container child ViewNoteBook.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.HeightRequest = 26;
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.LabelInformation = new global::Gtk.Label ();
			this.LabelInformation.Name = "LabelInformation";
			this.LabelInformation.Xalign = 0F;
			this.LabelInformation.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox1.Add (this.LabelInformation);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.LabelInformation]));
			w54.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterInfo = new global::Gtk.ToggleButton ();
			this.ButtonFilterInfo.CanFocus = true;
			this.ButtonFilterInfo.Name = "ButtonFilterInfo";
			this.ButtonFilterInfo.UseUnderline = true;
			global::Gtk.Image w55 = new global::Gtk.Image ();
			w55.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-info", global::Gtk.IconSize.Menu);
			this.ButtonFilterInfo.Image = w55;
			this.hbox1.Add (this.ButtonFilterInfo);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterInfo]));
			w56.Position = 1;
			w56.Expand = false;
			w56.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterWarning = new global::Gtk.ToggleButton ();
			this.ButtonFilterWarning.CanFocus = true;
			this.ButtonFilterWarning.Name = "ButtonFilterWarning";
			this.ButtonFilterWarning.UseUnderline = true;
			global::Gtk.Image w57 = new global::Gtk.Image ();
			w57.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-warning", global::Gtk.IconSize.Menu);
			this.ButtonFilterWarning.Image = w57;
			this.hbox1.Add (this.ButtonFilterWarning);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterWarning]));
			w58.Position = 2;
			w58.Expand = false;
			w58.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterError = new global::Gtk.ToggleButton ();
			this.ButtonFilterError.CanFocus = true;
			this.ButtonFilterError.Name = "ButtonFilterError";
			this.ButtonFilterError.UseUnderline = true;
			global::Gtk.Image w59 = new global::Gtk.Image ();
			w59.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-error", global::Gtk.IconSize.Menu);
			this.ButtonFilterError.Image = w59;
			this.hbox1.Add (this.ButtonFilterError);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterError]));
			w60.Position = 3;
			w60.Expand = false;
			w60.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.ButtonFilterQuestion = new global::Gtk.ToggleButton ();
			this.ButtonFilterQuestion.CanFocus = true;
			this.ButtonFilterQuestion.Name = "ButtonFilterQuestion";
			this.ButtonFilterQuestion.UseUnderline = true;
			global::Gtk.Image w61 = new global::Gtk.Image ();
			w61.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dialog-question", global::Gtk.IconSize.Menu);
			this.ButtonFilterQuestion.Image = w61;
			this.hbox1.Add (this.ButtonFilterQuestion);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.ButtonFilterQuestion]));
			w62.Position = 4;
			w62.Expand = false;
			w62.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.EraseOutput = new global::Gtk.Button ();
			this.EraseOutput.CanFocus = true;
			this.EraseOutput.Name = "EraseOutput";
			this.EraseOutput.UseUnderline = true;
			global::Gtk.Image w63 = new global::Gtk.Image ();
			w63.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			this.EraseOutput.Image = w63;
			this.hbox1.Add (this.EraseOutput);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.EraseOutput]));
			w64.Position = 5;
			w64.Expand = false;
			w64.Fill = false;
			this.eventbox1.Add (this.hbox1);
			this.vbox4.Add (this.eventbox1);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.eventbox1]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.OutputTreeview = new global::Gtk.TreeView ();
			this.OutputTreeview.CanFocus = true;
			this.OutputTreeview.Name = "OutputTreeview";
			this.GtkScrolledWindow1.Add (this.OutputTreeview);
			this.vbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
			w68.Position = 1;
			this.ViewNoteBook.Add (this.vbox4);
			// Notebook tab
			this.OutputTab = new global::Gtk.Label ();
			this.OutputTab.Name = "OutputTab";
			this.OutputTab.LabelProp = global::Mono.Unix.Catalog.GetString ("OutputTab");
			this.ViewNoteBook.SetTabLabel (this.vbox4, this.OutputTab);
			this.OutputTab.ShowAll ();
			// Container child ViewNoteBook.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.eventbox2 = new global::Gtk.EventBox ();
			this.eventbox2.HeightRequest = 26;
			this.eventbox2.Name = "eventbox2";
			// Container child eventbox2.Gtk.Container+ContainerChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LabelHistoric = new global::Gtk.Label ();
			this.LabelHistoric.Name = "LabelHistoric";
			this.LabelHistoric.Xalign = 0F;
			this.LabelHistoric.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox3.Add (this.LabelHistoric);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LabelHistoric]));
			w70.Position = 0;
			this.eventbox2.Add (this.hbox3);
			this.vbox5.Add (this.eventbox2);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.eventbox2]));
			w72.Position = 0;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.HistoricTreeView = new global::Gtk.TreeView ();
			this.HistoricTreeView.CanFocus = true;
			this.HistoricTreeView.Name = "HistoricTreeView";
			this.GtkScrolledWindow2.Add (this.HistoricTreeView);
			this.vbox5.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow2]));
			w74.Position = 1;
			this.ViewNoteBook.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w75 = ((global::Gtk.Notebook.NotebookChild)(this.ViewNoteBook [this.vbox5]));
			w75.Position = 1;
			// Notebook tab
			this.HistoryTab = new global::Gtk.Label ();
			this.HistoryTab.Name = "HistoryTab";
			this.HistoryTab.LabelProp = global::Mono.Unix.Catalog.GetString ("HistoryTab");
			this.ViewNoteBook.SetTabLabel (this.vbox5, this.HistoryTab);
			this.HistoryTab.ShowAll ();
			// Container child ViewNoteBook.Gtk.Notebook+NotebookChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.eventbox3 = new global::Gtk.EventBox ();
			this.eventbox3.HeightRequest = 26;
			this.eventbox3.Name = "eventbox3";
			// Container child eventbox3.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.LabelCompilLog = new global::Gtk.Label ();
			this.LabelCompilLog.Name = "LabelCompilLog";
			this.LabelCompilLog.Xalign = 0F;
			this.LabelCompilLog.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox5.Add (this.LabelCompilLog);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.LabelCompilLog]));
			w76.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.ExportLogButton = new global::Gtk.Button ();
			this.ExportLogButton.CanFocus = true;
			this.ExportLogButton.Name = "ExportLogButton";
			this.ExportLogButton.UseUnderline = true;
			this.ExportLogButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox5.Add (this.ExportLogButton);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.ExportLogButton]));
			w77.Position = 4;
			w77.Expand = false;
			w77.Fill = false;
			this.eventbox3.Add (this.hbox5);
			this.vbox6.Add (this.eventbox3);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.eventbox3]));
			w79.Position = 0;
			w79.Expand = false;
			w79.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.TextViewCompilLog = new global::Gtk.TextView ();
			this.TextViewCompilLog.CanFocus = true;
			this.TextViewCompilLog.Name = "TextViewCompilLog";
			this.GtkScrolledWindow.Add (this.TextViewCompilLog);
			this.vbox6.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.GtkScrolledWindow]));
			w81.Position = 1;
			this.ViewNoteBook.Add (this.vbox6);
			global::Gtk.Notebook.NotebookChild w82 = ((global::Gtk.Notebook.NotebookChild)(this.ViewNoteBook [this.vbox6]));
			w82.Position = 2;
			// Notebook tab
			this.CompilLog = new global::Gtk.Label ();
			this.CompilLog.Name = "CompilLog";
			this.CompilLog.LabelProp = global::Mono.Unix.Catalog.GetString ("CompilLog");
			this.ViewNoteBook.SetTabLabel (this.vbox6, this.CompilLog);
			this.CompilLog.ShowAll ();
			this.vpaned1.Add (this.ViewNoteBook);
			this.hpaned1.Add (this.vpaned1);
			global::Gtk.Paned.PanedChild w84 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned1]));
			w84.Resize = false;
			w84.Shrink = false;
			this.vbox1.Add (this.hpaned1);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
			w85.Position = 3;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.HeightRequest = 25;
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.LabelInfoProject = new global::Gtk.Label ();
			this.LabelInfoProject.Name = "LabelInfoProject";
			this.LabelInfoProject.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox4.Add (this.LabelInfoProject);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.LabelInfoProject]));
			w86.Position = 0;
			w86.Expand = false;
			w86.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vseparator3 = new global::Gtk.VSeparator ();
			this.vseparator3.Name = "vseparator3";
			this.hbox4.Add (this.vseparator3);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vseparator3]));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.LabelPathProject = new global::Gtk.Label ();
			this.LabelPathProject.Name = "LabelPathProject";
			this.LabelPathProject.Xalign = 0F;
			this.LabelPathProject.LabelProp = global::Mono.Unix.Catalog.GetString ("label1");
			this.hbox4.Add (this.LabelPathProject);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.LabelPathProject]));
			w88.Position = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ProgressBar = new global::Gtk.ProgressBar ();
			this.ProgressBar.Name = "ProgressBar";
			this.ProgressBar.Text = "";
			this.ProgressBar.PulseStep = 0D;
			this.hbox4.Add (this.ProgressBar);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ProgressBar]));
			w89.Position = 3;
			w89.Expand = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ExpendHistoryPanel = new global::Gtk.Button ();
			this.ExpendHistoryPanel.CanFocus = true;
			this.ExpendHistoryPanel.Name = "ExpendHistoryPanel";
			this.ExpendHistoryPanel.UseUnderline = true;
			this.ExpendHistoryPanel.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w90 = new global::Gtk.Image ();
			w90.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Menu);
			this.ExpendHistoryPanel.Image = w90;
			this.hbox4.Add (this.ExpendHistoryPanel);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ExpendHistoryPanel]));
			w91.Position = 4;
			w91.Expand = false;
			w91.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.ReduceHistoryPanel = new global::Gtk.Button ();
			this.ReduceHistoryPanel.CanFocus = true;
			this.ReduceHistoryPanel.Name = "ReduceHistoryPanel";
			this.ReduceHistoryPanel.UseUnderline = true;
			this.ReduceHistoryPanel.Relief = ((global::Gtk.ReliefStyle)(2));
			global::Gtk.Image w92 = new global::Gtk.Image ();
			w92.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Menu);
			this.ReduceHistoryPanel.Image = w92;
			this.hbox4.Add (this.ReduceHistoryPanel);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.ReduceHistoryPanel]));
			w93.Position = 5;
			w93.Expand = false;
			w93.Fill = false;
			this.vbox1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
			w94.Position = 4;
			w94.Expand = false;
			w94.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1530;
			this.DefaultHeight = 1224;
			this.ButtonReadEthernet.Hide ();
			this.Expand.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.newAction.Activated += new global::System.EventHandler (this.OnFileActionActivated);
			this.openAction.Activated += new global::System.EventHandler (this.OnOpenActionActivated);
			this.CreateConfigurationAction.Activated += new global::System.EventHandler (this.OnCreateConfigurationActionActivated);
			this.goForwardAction.Activated += new global::System.EventHandler (this.OnGoForwardActionActivated);
			this.goBackAction.Activated += new global::System.EventHandler (this.OnGoBackActionActivated);
			this.closeAction.Activated += new global::System.EventHandler (this.OnCloseActionActivated);
			this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
			this.undoAction.Activated += new global::System.EventHandler (this.OnUndoActionActivated);
			this.redoAction.Activated += new global::System.EventHandler (this.OnRedoActionActivated);
			this.MyPreferenceAction.Activated += new global::System.EventHandler (this.OnMyPreferenceActionActivated);
			this.saveAction.Activated += new global::System.EventHandler (this.OnSaveActionActivated);
			this.saveAsAction.Activated += new global::System.EventHandler (this.OnSaveAsActionActivated);
			this.aboutAction.Activated += new global::System.EventHandler (this.OnAboutActionActivated);
			this.ButtonNewProject.Clicked += new global::System.EventHandler (this.OnButtonNewProjectClicked);
			this.ButtonOpenProject.Clicked += new global::System.EventHandler (this.OnButtonOpenProjectClicked);
			this.ButtonSaveProject.Clicked += new global::System.EventHandler (this.OnButtonSaveProjectClicked);
			this.ButtonSaveAllProject.Clicked += new global::System.EventHandler (this.OnButtonSaveAllProjectClicked);
			this.UndoButton.Clicked += new global::System.EventHandler (this.OnUndoButtonClicked);
			this.RedoButton.Clicked += new global::System.EventHandler (this.OnRedoButtonClicked);
			this.ButtonReloadUSB.Clicked += new global::System.EventHandler (this.OnButtonReloadUSBClicked);
			this.ButtonReadEthernet.Clicked += new global::System.EventHandler (this.OnButtonReadEthernetClicked);
			this.Up.Clicked += new global::System.EventHandler (this.OnUpClicked);
			this.Down.Clicked += new global::System.EventHandler (this.OnDownClicked);
			this.Reduce.Clicked += new global::System.EventHandler (this.OnReduceClicked);
			this.Expand.Clicked += new global::System.EventHandler (this.OnIncreaseClicked);
			this.ExplorerTreeView.CursorChanged += new global::System.EventHandler (this.OnExplorerTreeViewCursorChanged);
			this.ButtonNew1.Clicked += new global::System.EventHandler (this.OnButtonNew1Clicked);
			this.MainNoteBook.SwitchPage += new global::Gtk.SwitchPageHandler (this.OnMainNoteBookSwitchPage);
			this.ButtonFilterInfo.Toggled += new global::System.EventHandler (this.OnButtonFilterInfoToggled);
			this.ButtonFilterWarning.Toggled += new global::System.EventHandler (this.OnButtonFilterWarningToggled);
			this.ButtonFilterError.Toggled += new global::System.EventHandler (this.OnButtonFilterErrorToggled);
			this.ButtonFilterQuestion.Toggled += new global::System.EventHandler (this.OnButtonFilterQuestionToggled);
			this.EraseOutput.Clicked += new global::System.EventHandler (this.OnEraseOutputClicked);
			this.HistoricTreeView.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnHistoricTreeViewButtonReleaseEvent);
			this.ExpendHistoryPanel.Clicked += new global::System.EventHandler (this.OnExpendHistoryPanelClicked);
			this.ReduceHistoryPanel.Clicked += new global::System.EventHandler (this.OnReduceHistoryPanelClicked);
		}
	}
}
